//go:build go1.22

// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ParticipantViewKind.
const (
	Agent  ParticipantViewKind = "agent"
	Human  ParticipantViewKind = "human"
	System ParticipantViewKind = "system"
)

// Valid indicates whether the value is a known member of the ParticipantViewKind enum.
func (e ParticipantViewKind) Valid() bool {
	switch e {
	case Agent:
		return true
	case Human:
		return true
	case System:
		return true
	default:
		return false
	}
}

// Defines values for RoomCommandCommandKind.
const (
	CloseThread   RoomCommandCommandKind = "close_thread"
	CreateRoom    RoomCommandCommandKind = "create_room"
	EndorseIntent RoomCommandCommandKind = "endorse_intent"
	ForkThread    RoomCommandCommandKind = "fork_thread"
	MergeThread   RoomCommandCommandKind = "merge_thread"
	PauseRoom     RoomCommandCommandKind = "pause_room"
	PauseThread   RoomCommandCommandKind = "pause_thread"
	PostMessage   RoomCommandCommandKind = "post_message"
	RenameRoom    RoomCommandCommandKind = "rename_room"
	ReopenThread  RoomCommandCommandKind = "reopen_thread"
	ResumeRoom    RoomCommandCommandKind = "resume_room"
	ResumeThread  RoomCommandCommandKind = "resume_thread"
	SetPolicy     RoomCommandCommandKind = "set_policy"
)

// Valid indicates whether the value is a known member of the RoomCommandCommandKind enum.
func (e RoomCommandCommandKind) Valid() bool {
	switch e {
	case CloseThread:
		return true
	case CreateRoom:
		return true
	case EndorseIntent:
		return true
	case ForkThread:
		return true
	case MergeThread:
		return true
	case PauseRoom:
		return true
	case PauseThread:
		return true
	case PostMessage:
		return true
	case RenameRoom:
		return true
	case ReopenThread:
		return true
	case ResumeRoom:
		return true
	case ResumeThread:
		return true
	case SetPolicy:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotThreadsState.
const (
	Active SnapshotThreadsState = "active"
	Closed SnapshotThreadsState = "closed"
	Merged SnapshotThreadsState = "merged"
	Paused SnapshotThreadsState = "paused"
)

// Valid indicates whether the value is a known member of the SnapshotThreadsState enum.
func (e SnapshotThreadsState) Valid() bool {
	switch e {
	case Active:
		return true
	case Closed:
		return true
	case Merged:
		return true
	case Paused:
		return true
	default:
		return false
	}
}

// Defines values for GetHealthz200JSONResponseBodyStatus.
const (
	Ok GetHealthz200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the GetHealthz200JSONResponseBodyStatus enum.
func (e GetHealthz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for AddHarnessExecutable201JSONResponseBodyStatus.
const (
	Registered AddHarnessExecutable201JSONResponseBodyStatus = "registered"
)

// Valid indicates whether the value is a known member of the AddHarnessExecutable201JSONResponseBodyStatus enum.
func (e AddHarnessExecutable201JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Registered:
		return true
	default:
		return false
	}
}

// Defines values for DisableHarnessExecutable200JSONResponseBodyEnabled.
const (
	False DisableHarnessExecutable200JSONResponseBodyEnabled = false
)

// Valid indicates whether the value is a known member of the DisableHarnessExecutable200JSONResponseBodyEnabled enum.
func (e DisableHarnessExecutable200JSONResponseBodyEnabled) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// Defines values for EnableHarnessExecutable200JSONResponseBodyEnabled.
const (
	True EnableHarnessExecutable200JSONResponseBodyEnabled = true
)

// Valid indicates whether the value is a known member of the EnableHarnessExecutable200JSONResponseBodyEnabled enum.
func (e EnableHarnessExecutable200JSONResponseBodyEnabled) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// CommandResponse defines model for CommandResponse.
type CommandResponse struct {
	EventId     string `json:"event_id"`
	Replayed    bool   `json:"replayed"`
	RoomId      string `json:"room_id"`
	RoomVersion int64  `json:"room_version"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code 稳定错误码（transport 与 domain 映射）
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Executable defines model for Executable.
type Executable struct {
	Adapter string `json:"adapter"`

	// Channel 实例渠道（ADR-0012）：cli | app:codex-desktop | app:kimi-work
	Channel *string `json:"channel,omitempty"`

	// Digest sha256（版本固定门禁用）
	Digest       *string    `json:"digest,omitempty"`
	DiscoveredAt *time.Time `json:"discovered_at,omitempty"`

	// Distro WSL 运行面的发行版（native 为空）
	Distro  *string `json:"distro,omitempty"`
	Enabled bool    `json:"enabled"`

	// Id 注册表唯一 ID（adapter@runtime:path）
	Id string `json:"id"`

	// LoginState logged_in | logged_out | unknown
	LoginState *string `json:"login_state,omitempty"`
	Path       string  `json:"path"`

	// Priority 家族裁定优先级（数值小者优先；列表已按 adapter→priority→path 排序）
	Priority *int `json:"priority,omitempty"`

	// Runtime native | wsl
	Runtime string `json:"runtime"`

	// Source auto_scan | manual
	Source  *string `json:"source,omitempty"`
	Version *string `json:"version,omitempty"`
}

// ManualExecutableRequest defines model for ManualExecutableRequest.
type ManualExecutableRequest struct {
	Adapter string `json:"adapter"`

	// Channel 可选渠道覆盖（cli 或 app:<小写>），空值按 cli
	Channel *string `json:"channel,omitempty"`
	Distro  *string `json:"distro,omitempty"`
	Path    string  `json:"path"`
	Runtime string  `json:"runtime"`
	Version *string `json:"version,omitempty"`
}

// ParticipantView defines model for ParticipantView.
type ParticipantView struct {
	// Adapter agent 座位的适配器名（human 无此键）
	Adapter *string `json:"adapter,omitempty"`

	// Channel harness 渠道标签（cli/app:codex-desktop 等；无则省略）
	Channel *string `json:"channel,omitempty"`

	// DisplayName 引擎已知名字（Owner/Echo/Codex/Kimi 等）
	DisplayName   string              `json:"display_name"`
	Kind          ParticipantViewKind `json:"kind"`
	ParticipantId string              `json:"participant_id"`

	// SeatStatus seated（在座；离座语义随 UI 重设计后续切片定稿）
	SeatStatus string `json:"seat_status"`
}

// ParticipantViewKind defines model for ParticipantView.Kind.
type ParticipantViewKind string

// RoomCommand 命令信封（RFC-0001）。payload 按 command_kind 严格校验（未知字段拒绝）：
// create_room → CreateRoomPayload；post_message → PostMessagePayload；
// pause_room → PauseRoomPayload；resume_room → 空 payload；
// rename_room → RenameRoomPayload（UI 重设计切片 1；room.renamed 事件）；
// set_policy → PolicyParams（RFC-0003 §3.1.7；变更只在 round 边界生效）；
// endorse_intent → EndorseIntentPayload（OQ-17 人类保送，effect=grant）；
// fork/pause/resume/close/reopen/merge_thread → ThreadLifecyclePayload（RFC-0004 线程生命周期，
// 状态机转移校验；merge 在个人版单 owner 形态下为直接命令=确认权）。
type RoomCommand struct {
	CommandKind         RoomCommandCommandKind `json:"command_kind"`
	ExpectedRoomVersion int                    `json:"expected_room_version"`

	// IdempotencyKey UUIDv7（服务端按 tenant+key+kind 去重；同键异指纹 409）
	IdempotencyKey string                 `json:"idempotency_key"`
	IssuedAt       time.Time              `json:"issued_at"`
	Payload        map[string]interface{} `json:"payload"`
}

// RoomCommandCommandKind defines model for RoomCommand.CommandKind.
type RoomCommandCommandKind string

// RoomList defines model for RoomList.
type RoomList struct {
	Rooms []RoomSummary `json:"rooms"`
}

// RoomSummary defines model for RoomSummary.
type RoomSummary struct {
	CreatedAt time.Time `json:"created_at"`

	// DisplayName 最新 room.created/room.renamed 投影
	DisplayName string `json:"display_name"`

	// LastEventAt 该房间最新事件时间（无事件则等于 created_at）；列表按此倒序
	LastEventAt time.Time `json:"last_event_at"`

	// MessageCount message.posted 类事件数
	MessageCount int64 `json:"message_count"`

	// Paused 最新生命周期事件为 room.paused
	Paused bool   `json:"paused"`
	RoomId string `json:"room_id"`
}

// Snapshot defines model for Snapshot.
type Snapshot struct {
	AlgorithmVersion int64 `json:"algorithm_version"`

	// DisplayName 房间名（room.created/room.renamed 投影产物）
	DisplayName string `json:"display_name"`

	// Graph 显式关系边（forked_from/responds_to/merged_into + relations 类型化边）。推断边属结构投影（M3），接入后标 inferred=true——双视图显式与推断区分。
	Graph []struct {
		From     string `json:"from"`
		Inferred bool   `json:"inferred"`
		Kind     string `json:"kind"`
		To       string `json:"to"`
	} `json:"graph"`

	// Participants 参与者视图（装配层注入：本地 owner + 引擎座位；非投影产物——ADR-0011 注记，不进 room_version/水位语义）。
	Participants []ParticipantView `json:"participants"`

	// Policy 当前策略区（记分卡透明 OQ-17——权重/模式参数对成员可见、版本化）。
	Policy struct {
		IntentWindow   *string                 `json:"intent_window,omitempty"`
		Lambda         *float32                `json:"lambda,omitempty"`
		MaxSpeakers    *int                    `json:"max_speakers,omitempty"`
		Mode           *string                 `json:"mode,omitempty"`
		PolicyVersion  string                  `json:"policy_version"`
		ResponseCap    *int64                  `json:"response_cap,omitempty"`
		RevealStrategy *string                 `json:"reveal_strategy,omitempty"`
		Weights        *map[string]interface{} `json:"weights,omitempty"`
	} `json:"policy"`
	ProjectionVersion int64  `json:"projection_version"`
	RoomId            string `json:"room_id"`
	RoomVersion       int64  `json:"room_version"`

	// Scorecard 记分卡（R-08/OQ-17：intent 全量投影，band + 未选理由 + 保送状态）。
	Scorecard []struct {
		Action           *string    `json:"action,omitempty"`
		Endorsed         bool       `json:"endorsed"`
		IntentId         string     `json:"intent_id"`
		OccurredAt       *time.Time `json:"occurred_at,omitempty"`
		ParticipantId    string     `json:"participant_id"`
		PublicRationale  *string    `json:"public_rationale,omitempty"`
		RoundId          *string    `json:"round_id,omitempty"`
		ScoreBand        string     `json:"score_band"`
		Selected         bool       `json:"selected"`
		Type             *string    `json:"type,omitempty"`
		UnselectedReason *string    `json:"unselected_reason,omitempty"`
	} `json:"scorecard"`

	// Threads 线程投影（RFC-0004 生命周期状态 + fork 谱系 + 合并去向）。
	Threads []struct {
		Goal         *string              `json:"goal,omitempty"`
		MergedInto   *string              `json:"merged_into,omitempty"`
		MessageCount *int                 `json:"message_count,omitempty"`
		Parent       *string              `json:"parent,omitempty"`
		State        SnapshotThreadsState `json:"state"`
		ThreadId     string               `json:"thread_id"`
	} `json:"threads"`
	Timeline  []TimelineItem `json:"timeline"`
	Watermark string         `json:"watermark"`
}

// SnapshotThreadsState defines model for Snapshot.Threads.State.
type SnapshotThreadsState string

// TimelineItem defines model for TimelineItem.
type TimelineItem struct {
	ActorId    string    `json:"actor_id"`
	ActorKind  string    `json:"actor_kind"`
	Body       *string   `json:"body,omitempty"`
	EventId    string    `json:"event_id"`
	OccurredAt time.Time `json:"occurred_at"`
	Position   string    `json:"position"`
	ThreadId   *string   `json:"thread_id,omitempty"`
	Type       string    `json:"type"`
}

// ExecutableID defines model for ExecutableID.
type ExecutableID = string

// RoomID defines model for RoomID.
type RoomID = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// HarnessUnavailable defines model for HarnessUnavailable.
type HarnessUnavailable = Error

// Internal defines model for Internal.
type Internal = Error

// NotFound defines model for NotFound.
type NotFound = Error

// OriginRejected defines model for OriginRejected.
type OriginRejected = Error

// TooLarge defines model for TooLarge.
type TooLarge = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = Error

// GetHealthz200JSONResponseBodyStatus defines parameters for GetHealthz.
type GetHealthz200JSONResponseBodyStatus string

// AddHarnessExecutable201JSONResponseBodyStatus defines parameters for AddHarnessExecutable.
type AddHarnessExecutable201JSONResponseBodyStatus string

// DisableHarnessExecutable200JSONResponseBodyEnabled defines parameters for DisableHarnessExecutable.
type DisableHarnessExecutable200JSONResponseBodyEnabled bool

// EnableHarnessExecutable200JSONResponseBodyEnabled defines parameters for EnableHarnessExecutable.
type EnableHarnessExecutable200JSONResponseBodyEnabled bool

// SubscribeRoomEventsParams defines parameters for SubscribeRoomEvents.
type SubscribeRoomEventsParams struct {
	// Cursor opaque 游标（空 = 从头）；与 Last-Event-ID 同义，query 优先
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// AddHarnessExecutableJSONRequestBody defines body for AddHarnessExecutable for application/json ContentType.
type AddHarnessExecutableJSONRequestBody = ManualExecutableRequest

// CreateRoomJSONRequestBody defines body for CreateRoom for application/json ContentType.
type CreateRoomJSONRequestBody = RoomCommand

// SubmitRoomCommandJSONRequestBody defines body for SubmitRoomCommand for application/json ContentType.
type SubmitRoomCommandJSONRequestBody = RoomCommand

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealthz 存活探针
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// ListHarnessExecutables 宿主扫描到的 agent CLI 注册表
	// (GET /v1/harness/executables)
	ListHarnessExecutables(w http.ResponseWriter, r *http.Request)
	// AddHarnessExecutable 手动登记 agent CLI（探测失败拒收）
	// (POST /v1/harness/executables)
	AddHarnessExecutable(w http.ResponseWriter, r *http.Request)
	// DisableHarnessExecutable 禁用可执行项（座位随 resync 撤出）
	// (POST /v1/harness/executables/{id}/disable)
	DisableHarnessExecutable(w http.ResponseWriter, r *http.Request, id ExecutableID)
	// EnableHarnessExecutable 启用可执行项（登录门控；启用后 ≤10s 入座，无需重启）
	// (POST /v1/harness/executables/{id}/enable)
	EnableHarnessExecutable(w http.ResponseWriter, r *http.Request, id ExecutableID)
	// GetOwnerBootstrap 第一方客户端引导：返回 owner token（跨源门保护）
	// (GET /v1/owner/bootstrap)
	GetOwnerBootstrap(w http.ResponseWriter, r *http.Request)
	// ListRooms 房间列表（UI 重设计切片 1）
	// (GET /v1/rooms)
	ListRooms(w http.ResponseWriter, r *http.Request)
	// CreateRoom 创建房间（create_room 命令）
	// (POST /v1/rooms)
	CreateRoom(w http.ResponseWriter, r *http.Request)
	// SubmitRoomCommand 提交房间命令（post_message / pause_room / resume_room / rename_room 等）
	// (POST /v1/rooms/{room_id}/commands)
	SubmitRoomCommand(w http.ResponseWriter, r *http.Request, roomId RoomID)
	// SubscribeRoomEvents SSE 订阅房间事件流（opaque cursor 续传）
	// (GET /v1/rooms/{room_id}/events)
	SubscribeRoomEvents(w http.ResponseWriter, r *http.Request, roomId RoomID, params SubscribeRoomEventsParams)
	// GetRoomSnapshot 快照（版本 + 水位 + 投影/算法版本 + Timeline 投影 + 房间名/参与者视图）
	// (GET /v1/rooms/{room_id}/snapshot)
	GetRoomSnapshot(w http.ResponseWriter, r *http.Request, roomId RoomID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHarnessExecutables operation middleware
func (siw *ServerInterfaceWrapper) ListHarnessExecutables(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHarnessExecutables(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddHarnessExecutable operation middleware
func (siw *ServerInterfaceWrapper) AddHarnessExecutable(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddHarnessExecutable(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DisableHarnessExecutable operation middleware
func (siw *ServerInterfaceWrapper) DisableHarnessExecutable(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExecutableID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DisableHarnessExecutable(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnableHarnessExecutable operation middleware
func (siw *ServerInterfaceWrapper) EnableHarnessExecutable(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExecutableID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnableHarnessExecutable(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOwnerBootstrap operation middleware
func (siw *ServerInterfaceWrapper) GetOwnerBootstrap(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOwnerBootstrap(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRooms operation middleware
func (siw *ServerInterfaceWrapper) ListRooms(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRooms(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRoom operation middleware
func (siw *ServerInterfaceWrapper) CreateRoom(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRoom(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitRoomCommand operation middleware
func (siw *ServerInterfaceWrapper) SubmitRoomCommand(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "room_id" -------------
	var roomId RoomID

	err = runtime.BindStyledParameterWithOptions("simple", "room_id", r.PathValue("room_id"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "room_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitRoomCommand(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubscribeRoomEvents operation middleware
func (siw *ServerInterfaceWrapper) SubscribeRoomEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "room_id" -------------
	var roomId RoomID

	err = runtime.BindStyledParameterWithOptions("simple", "room_id", r.PathValue("room_id"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "room_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeRoomEventsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubscribeRoomEvents(w, r, roomId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoomSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetRoomSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "room_id" -------------
	var roomId RoomID

	err = runtime.BindStyledParameterWithOptions("simple", "room_id", r.PathValue("room_id"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "room_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomSnapshot(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/rooms", wrapper.ListRooms)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/rooms", wrapper.CreateRoom)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/rooms/{room_id}/commands", wrapper.SubmitRoomCommand)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/rooms/{room_id}/events", wrapper.SubscribeRoomEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/rooms/{room_id}/snapshot", wrapper.GetRoomSnapshot)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/owner/bootstrap", wrapper.GetOwnerBootstrap)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/harness/executables", wrapper.ListHarnessExecutables)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/harness/executables", wrapper.AddHarnessExecutable)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/harness/executables/{id}/enable", wrapper.EnableHarnessExecutable)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/harness/executables/{id}/disable", wrapper.DisableHarnessExecutable)

	return m
}
