//go:build go1.22

// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ClosureSummaryClosureType.
const (
	ClosureSummaryClosureTypeBoundedDisagreement ClosureSummaryClosureType = "bounded_disagreement"
	ClosureSummaryClosureTypeConsensus           ClosureSummaryClosureType = "consensus"
)

// Valid indicates whether the value is a known member of the ClosureSummaryClosureType enum.
func (e ClosureSummaryClosureType) Valid() bool {
	switch e {
	case ClosureSummaryClosureTypeBoundedDisagreement:
		return true
	case ClosureSummaryClosureTypeConsensus:
		return true
	default:
		return false
	}
}

// Defines values for ClosureSummaryState.
const (
	ClosureSummaryStateAccepted ClosureSummaryState = "accepted"
	ClosureSummaryStatePending  ClosureSummaryState = "pending"
	ClosureSummaryStateRejected ClosureSummaryState = "rejected"
)

// Valid indicates whether the value is a known member of the ClosureSummaryState enum.
func (e ClosureSummaryState) Valid() bool {
	switch e {
	case ClosureSummaryStateAccepted:
		return true
	case ClosureSummaryStatePending:
		return true
	case ClosureSummaryStateRejected:
		return true
	default:
		return false
	}
}

// Defines values for EvidenceRequestViewStatus.
const (
	EvidenceRequestViewStatusDismissed EvidenceRequestViewStatus = "dismissed"
	EvidenceRequestViewStatusOpen      EvidenceRequestViewStatus = "open"
	EvidenceRequestViewStatusResolved  EvidenceRequestViewStatus = "resolved"
)

// Valid indicates whether the value is a known member of the EvidenceRequestViewStatus enum.
func (e EvidenceRequestViewStatus) Valid() bool {
	switch e {
	case EvidenceRequestViewStatusDismissed:
		return true
	case EvidenceRequestViewStatusOpen:
		return true
	case EvidenceRequestViewStatusResolved:
		return true
	default:
		return false
	}
}

// Defines values for MemoryViewCapsulesClosureType.
const (
	MemoryViewCapsulesClosureTypeBoundedDisagreement MemoryViewCapsulesClosureType = "bounded_disagreement"
	MemoryViewCapsulesClosureTypeConsensus           MemoryViewCapsulesClosureType = "consensus"
)

// Valid indicates whether the value is a known member of the MemoryViewCapsulesClosureType enum.
func (e MemoryViewCapsulesClosureType) Valid() bool {
	switch e {
	case MemoryViewCapsulesClosureTypeBoundedDisagreement:
		return true
	case MemoryViewCapsulesClosureTypeConsensus:
		return true
	default:
		return false
	}
}

// Defines values for ParticipantViewKind.
const (
	ParticipantViewKindAgent  ParticipantViewKind = "agent"
	ParticipantViewKindHuman  ParticipantViewKind = "human"
	ParticipantViewKindSystem ParticipantViewKind = "system"
)

// Valid indicates whether the value is a known member of the ParticipantViewKind enum.
func (e ParticipantViewKind) Valid() bool {
	switch e {
	case ParticipantViewKindAgent:
		return true
	case ParticipantViewKindHuman:
		return true
	case ParticipantViewKindSystem:
		return true
	default:
		return false
	}
}

// Defines values for RoomCommandCommandKind.
const (
	AcceptClosure          RoomCommandCommandKind = "accept_closure"
	CloseThread            RoomCommandCommandKind = "close_thread"
	CreateEvidenceRequest  RoomCommandCommandKind = "create_evidence_request"
	CreateRoom             RoomCommandCommandKind = "create_room"
	DeleteRoom             RoomCommandCommandKind = "delete_room"
	EditMemory             RoomCommandCommandKind = "edit_memory"
	EndorseIntent          RoomCommandCommandKind = "endorse_intent"
	ForkThread             RoomCommandCommandKind = "fork_thread"
	InviteAgent            RoomCommandCommandKind = "invite_agent"
	MergeThread            RoomCommandCommandKind = "merge_thread"
	PauseRoom              RoomCommandCommandKind = "pause_room"
	PauseThread            RoomCommandCommandKind = "pause_thread"
	PostMessage            RoomCommandCommandKind = "post_message"
	ProposeClosure         RoomCommandCommandKind = "propose_closure"
	RenameRoom             RoomCommandCommandKind = "rename_room"
	ReopenThread           RoomCommandCommandKind = "reopen_thread"
	ResolveEvidenceRequest RoomCommandCommandKind = "resolve_evidence_request"
	ResolveTask            RoomCommandCommandKind = "resolve_task"
	ResumeRoom             RoomCommandCommandKind = "resume_room"
	ResumeThread           RoomCommandCommandKind = "resume_thread"
)

// Valid indicates whether the value is a known member of the RoomCommandCommandKind enum.
func (e RoomCommandCommandKind) Valid() bool {
	switch e {
	case AcceptClosure:
		return true
	case CloseThread:
		return true
	case CreateEvidenceRequest:
		return true
	case CreateRoom:
		return true
	case DeleteRoom:
		return true
	case EditMemory:
		return true
	case EndorseIntent:
		return true
	case ForkThread:
		return true
	case InviteAgent:
		return true
	case MergeThread:
		return true
	case PauseRoom:
		return true
	case PauseThread:
		return true
	case PostMessage:
		return true
	case ProposeClosure:
		return true
	case RenameRoom:
		return true
	case ReopenThread:
		return true
	case ResolveEvidenceRequest:
		return true
	case ResolveTask:
		return true
	case ResumeRoom:
		return true
	case ResumeThread:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeOptionsDefaultSource.
const (
	RuntimeOptionsDefaultSourceBuiltin RuntimeOptionsDefaultSource = "builtin"
	RuntimeOptionsDefaultSourceConfig  RuntimeOptionsDefaultSource = "config"
	RuntimeOptionsDefaultSourceEmpty   RuntimeOptionsDefaultSource = ""
)

// Valid indicates whether the value is a known member of the RuntimeOptionsDefaultSource enum.
func (e RuntimeOptionsDefaultSource) Valid() bool {
	switch e {
	case RuntimeOptionsDefaultSourceBuiltin:
		return true
	case RuntimeOptionsDefaultSourceConfig:
		return true
	case RuntimeOptionsDefaultSourceEmpty:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeUpdateRequestReasoningEffort.
const (
	RuntimeUpdateRequestReasoningEffortEmpty   RuntimeUpdateRequestReasoningEffort = ""
	RuntimeUpdateRequestReasoningEffortHigh    RuntimeUpdateRequestReasoningEffort = "high"
	RuntimeUpdateRequestReasoningEffortLow     RuntimeUpdateRequestReasoningEffort = "low"
	RuntimeUpdateRequestReasoningEffortMedium  RuntimeUpdateRequestReasoningEffort = "medium"
	RuntimeUpdateRequestReasoningEffortMinimal RuntimeUpdateRequestReasoningEffort = "minimal"
	RuntimeUpdateRequestReasoningEffortXhigh   RuntimeUpdateRequestReasoningEffort = "xhigh"
)

// Valid indicates whether the value is a known member of the RuntimeUpdateRequestReasoningEffort enum.
func (e RuntimeUpdateRequestReasoningEffort) Valid() bool {
	switch e {
	case RuntimeUpdateRequestReasoningEffortEmpty:
		return true
	case RuntimeUpdateRequestReasoningEffortHigh:
		return true
	case RuntimeUpdateRequestReasoningEffortLow:
		return true
	case RuntimeUpdateRequestReasoningEffortMedium:
		return true
	case RuntimeUpdateRequestReasoningEffortMinimal:
		return true
	case RuntimeUpdateRequestReasoningEffortXhigh:
		return true
	default:
		return false
	}
}

// Defines values for SearchHitActorKind.
const (
	SearchHitActorKindAgent  SearchHitActorKind = "agent"
	SearchHitActorKindHuman  SearchHitActorKind = "human"
	SearchHitActorKindSystem SearchHitActorKind = "system"
)

// Valid indicates whether the value is a known member of the SearchHitActorKind enum.
func (e SearchHitActorKind) Valid() bool {
	switch e {
	case SearchHitActorKindAgent:
		return true
	case SearchHitActorKindHuman:
		return true
	case SearchHitActorKindSystem:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotThreadsState.
const (
	Active SnapshotThreadsState = "active"
	Closed SnapshotThreadsState = "closed"
	Merged SnapshotThreadsState = "merged"
	Paused SnapshotThreadsState = "paused"
)

// Valid indicates whether the value is a known member of the SnapshotThreadsState enum.
func (e SnapshotThreadsState) Valid() bool {
	switch e {
	case Active:
		return true
	case Closed:
		return true
	case Merged:
		return true
	case Paused:
		return true
	default:
		return false
	}
}

// Defines values for TaskItemStatus.
const (
	TaskItemStatusDelivered TaskItemStatus = "delivered"
	TaskItemStatusDismissed TaskItemStatus = "dismissed"
	TaskItemStatusPending   TaskItemStatus = "pending"
)

// Valid indicates whether the value is a known member of the TaskItemStatus enum.
func (e TaskItemStatus) Valid() bool {
	switch e {
	case TaskItemStatusDelivered:
		return true
	case TaskItemStatusDismissed:
		return true
	case TaskItemStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for GetHealthz200JSONResponseBodyStatus.
const (
	Ok GetHealthz200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the GetHealthz200JSONResponseBodyStatus enum.
func (e GetHealthz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for AddHarnessExecutable201JSONResponseBodyStatus.
const (
	Registered AddHarnessExecutable201JSONResponseBodyStatus = "registered"
)

// Valid indicates whether the value is a known member of the AddHarnessExecutable201JSONResponseBodyStatus enum.
func (e AddHarnessExecutable201JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Registered:
		return true
	default:
		return false
	}
}

// Defines values for DisableHarnessExecutable200JSONResponseBodyEnabled.
const (
	False DisableHarnessExecutable200JSONResponseBodyEnabled = false
)

// Valid indicates whether the value is a known member of the DisableHarnessExecutable200JSONResponseBodyEnabled enum.
func (e DisableHarnessExecutable200JSONResponseBodyEnabled) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// Defines values for EnableHarnessExecutable200JSONResponseBodyEnabled.
const (
	True EnableHarnessExecutable200JSONResponseBodyEnabled = true
)

// Valid indicates whether the value is a known member of the EnableHarnessExecutable200JSONResponseBodyEnabled enum.
func (e EnableHarnessExecutable200JSONResponseBodyEnabled) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// ClosureSummary defines model for ClosureSummary.
type ClosureSummary struct {
	ClosureId   string                     `json:"closure_id"`
	ClosureType *ClosureSummaryClosureType `json:"closure_type,omitempty"`
	Concluded   int                        `json:"concluded"`
	Evaluated   int                        `json:"evaluated"`
	Objected    int                        `json:"objected"`
	Ready       bool                       `json:"ready"`
	Reason      *string                    `json:"reason,omitempty"`
	State       ClosureSummaryState        `json:"state"`
	ThreadId    string                     `json:"thread_id"`
}

// ClosureSummaryClosureType defines model for ClosureSummary.ClosureType.
type ClosureSummaryClosureType string

// ClosureSummaryState defines model for ClosureSummary.State.
type ClosureSummaryState string

// CommandResponse defines model for CommandResponse.
type CommandResponse struct {
	EventId     string `json:"event_id"`
	Replayed    bool   `json:"replayed"`
	RoomId      string `json:"room_id"`
	RoomVersion int64  `json:"room_version"`
}

// DevNote defines model for DevNote.
type DevNote struct {
	EventId    string                 `json:"event_id"`
	OccurredAt time.Time              `json:"occurred_at"`
	Payload    map[string]interface{} `json:"payload"`
	Position   string                 `json:"position"`
	Type       string                 `json:"type"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code 稳定错误码（transport 与 domain 映射）
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// EvidenceRequestView defines model for EvidenceRequestView.
type EvidenceRequestView struct {
	AcceptanceCriteria       *string                   `json:"acceptance_criteria,omitempty"`
	ClaimId                  *string                   `json:"claim_id,omitempty"`
	EvidenceRefs             *[]string                 `json:"evidence_refs,omitempty"`
	Owners                   *[]string                 `json:"owners,omitempty"`
	Question                 string                    `json:"question"`
	ReopenThreadOnResolution *bool                     `json:"reopen_thread_on_resolution,omitempty"`
	RequestId                string                    `json:"request_id"`
	RequiredEvidence         *[]string                 `json:"required_evidence,omitempty"`
	Status                   EvidenceRequestViewStatus `json:"status"`
}

// EvidenceRequestViewStatus defines model for EvidenceRequestView.Status.
type EvidenceRequestViewStatus string

// Executable defines model for Executable.
type Executable struct {
	Adapter string `json:"adapter"`

	// Channel 实例渠道（ADR-0012）：cli | app:codex-desktop | app:kimi-work
	Channel *string `json:"channel,omitempty"`

	// Digest sha256（版本固定门禁用）
	Digest       *string    `json:"digest,omitempty"`
	DiscoveredAt *time.Time `json:"discovered_at,omitempty"`

	// Distro WSL 运行面的发行版（native 为空）
	Distro  *string `json:"distro,omitempty"`
	Enabled bool    `json:"enabled"`

	// EvalModel 评估任务专用模型（手编；空 = 与生成同模型）
	EvalModel *string `json:"eval_model,omitempty"`

	// Id 注册表唯一 ID（adapter@runtime:path）
	Id string `json:"id"`

	// LoginState logged_in | logged_out | unknown
	LoginState *string `json:"login_state,omitempty"`

	// Model 模型覆盖（v1.48；空 = CLI 自身配置默认）
	Model *string `json:"model,omitempty"`
	Path  string  `json:"path"`

	// Priority 家族裁定优先级（数值小者优先；列表已按 adapter→priority→path 排序）
	Priority *int `json:"priority,omitempty"`

	// ReasoningEffort 思考强度（v1.48；仅 codex 有此面；空 = CLI 默认）
	ReasoningEffort *string `json:"reasoning_effort,omitempty"`

	// Runtime native | wsl
	Runtime string `json:"runtime"`

	// Source auto_scan | manual
	Source  *string `json:"source,omitempty"`
	Version *string `json:"version,omitempty"`
}

// ManualExecutableRequest defines model for ManualExecutableRequest.
type ManualExecutableRequest struct {
	Adapter string `json:"adapter"`

	// Channel 可选渠道覆盖（cli 或 app:<小写>），空值按 cli
	Channel *string `json:"channel,omitempty"`
	Distro  *string `json:"distro,omitempty"`
	Path    string  `json:"path"`
	Runtime string  `json:"runtime"`
	Version *string `json:"version,omitempty"`
}

// MemoryView 记忆查看面（GET /v1/rooms/{id}/memory）：编辑后胶囊 + 容量水位。
type MemoryView struct {
	// CapsuleBudget 恒常平面容量水位（Hermes 纪律：dropped_count > 0 即超预算——倒逼合并/编辑，不静默截断）
	CapsuleBudget struct {
		BudgetRunes   int `json:"budget_runes"`
		DroppedCount  int `json:"dropped_count"`
		InjectedCount int `json:"injected_count"`
		InjectedRunes int `json:"injected_runes"`
	} `json:"capsule_budget"`
	Capsules []struct {
		Assumptions []string                      `json:"assumptions"`
		ClosureId   string                        `json:"closure_id"`
		ClosureType MemoryViewCapsulesClosureType `json:"closure_type"`
		Conclusions []string                      `json:"conclusions"`

		// EditHistory 人工编辑留痕（正文在事件流；此处只留溯源位）
		EditHistory []struct {
			EditVersion int       `json:"edit_version"`
			EditedBy    string    `json:"edited_by"`
			EventId     string    `json:"event_id"`
			Note        *string   `json:"note,omitempty"`
			OccurredAt  time.Time `json:"occurred_at"`
		} `json:"edit_history"`
		Falsifiers   *[]string `json:"falsifiers,omitempty"`
		NamedDissent []struct {
			Basis         string `json:"basis"`
			ParticipantId string `json:"participant_id"`
		} `json:"named_dissent"`
		ReopenTriggers *[]string `json:"reopen_triggers,omitempty"`
		ThreadId       string    `json:"thread_id"`
		Watermark      *int64    `json:"watermark,omitempty"`
	} `json:"capsules"`
	RoomId string `json:"room_id"`
}

// MemoryViewCapsulesClosureType defines model for MemoryView.Capsules.ClosureType.
type MemoryViewCapsulesClosureType string

// ParticipantView defines model for ParticipantView.
type ParticipantView struct {
	// Adapter agent 座位的适配器名（human 无此键）
	Adapter *string `json:"adapter,omitempty"`

	// Channel harness 渠道标签（cli/app:codex-desktop 等；无则省略）
	Channel *string `json:"channel,omitempty"`

	// DisplayName 引擎已知名字（Owner/Echo/Codex/Kimi 等）
	DisplayName   string              `json:"display_name"`
	Kind          ParticipantViewKind `json:"kind"`
	ParticipantId string              `json:"participant_id"`

	// SeatStatus seated（在座；离座语义随 UI 重设计后续切片定稿）
	SeatStatus string `json:"seat_status"`
}

// ParticipantViewKind defines model for ParticipantView.Kind.
type ParticipantViewKind string

// RoomCommand 命令信封（RFC-0001）。payload 按 command_kind 严格校验（未知字段拒绝）：
// create_room → CreateRoomPayload；post_message → PostMessagePayload；
// pause_room → PauseRoomPayload；resume_room → 空 payload；
// rename_room → RenameRoomPayload（UI 重设计切片 1；room.renamed 事件）；
// endorse_intent → EndorseIntentPayload（OQ-17 人类保送，effect=grant）；
// invite_agent → {participant_id}（RFC-0001 Membership：participant.admitted 拉人）；
// fork/pause/resume/close/reopen/merge_thread → ThreadLifecyclePayload（RFC-0004 线程生命周期，
// 状态机转移校验；merge 在个人版单 owner 形态下为直接命令=确认权）。
type RoomCommand struct {
	CommandKind         RoomCommandCommandKind `json:"command_kind"`
	ExpectedRoomVersion int                    `json:"expected_room_version"`

	// IdempotencyKey UUIDv7（服务端按 tenant+key+kind 去重；同键异指纹 409）
	IdempotencyKey string                 `json:"idempotency_key"`
	IssuedAt       time.Time              `json:"issued_at"`
	Payload        map[string]interface{} `json:"payload"`
}

// RoomCommandCommandKind defines model for RoomCommand.CommandKind.
type RoomCommandCommandKind string

// RoomList defines model for RoomList.
type RoomList struct {
	Rooms []RoomSummary `json:"rooms"`
}

// RoomSummary defines model for RoomSummary.
type RoomSummary struct {
	CreatedAt time.Time `json:"created_at"`

	// DisplayName 最新 room.created/room.renamed 投影
	DisplayName string `json:"display_name"`

	// LastEventAt 该房间最新事件时间（无事件则等于 created_at）；列表按此倒序
	LastEventAt time.Time `json:"last_event_at"`

	// MessageCount message.posted 类事件数
	MessageCount int64 `json:"message_count"`

	// Paused 最新生命周期事件为 room.paused
	Paused bool   `json:"paused"`
	RoomId string `json:"room_id"`
}

// RuntimeOptions 模型候选与思考强度档位（设置页下拉数据源）+ 确定量默认值（v1.49）。
type RuntimeOptions struct {
	// DefaultEffort 不覆盖时的 CLI 默认思考强度（codex 官方默认 medium）
	DefaultEffort *string `json:"default_effort,omitempty"`

	// DefaultModel 不覆盖时的 CLI 默认模型（配置文件值优先；空 = CLI 内置预设未公布）
	DefaultModel *string `json:"default_model,omitempty"`

	// DefaultSource 默认值来源——config=CLI 配置文件；builtin=官方文档/出厂回退
	DefaultSource *RuntimeOptionsDefaultSource `json:"default_source,omitempty"`

	// Dynamic true = CLI 实查候选（kimi）；false = 无官方列表命令（空候选+自由输入）
	Dynamic bool `json:"dynamic"`

	// EffortLevels 思考强度档位（仅 codex 非空）
	EffortLevels []string `json:"effort_levels"`
	Models       []struct {
		DisplayName *string `json:"display_name,omitempty"`

		// Id 传给 CLI 的模型名（kimi 为 alias）
		Id string `json:"id"`
	} `json:"models"`
}

// RuntimeOptionsDefaultSource 默认值来源——config=CLI 配置文件；builtin=官方文档/出厂回退
type RuntimeOptionsDefaultSource string

// RuntimeUpdateRequest 运行参数更新体（全量替换；空串 = 清除覆盖回 CLI 默认）。
type RuntimeUpdateRequest struct {
	// Model 模型覆盖（codex/kimi 走 -m；mcode 走 --model provider/model）
	Model string `json:"model"`

	// ReasoningEffort 思考强度（仅 codex；空 = CLI 默认）
	ReasoningEffort RuntimeUpdateRequestReasoningEffort `json:"reasoning_effort"`
}

// RuntimeUpdateRequestReasoningEffort 思考强度（仅 codex；空 = CLI 默认）
type RuntimeUpdateRequestReasoningEffort string

// SearchHit 检索命中（对外视图：无 seq/tenant；position 供时间线跳转）。
type SearchHit struct {
	Actor      string             `json:"actor"`
	ActorKind  SearchHitActorKind `json:"actor_kind"`
	Body       string             `json:"body"`
	EventId    string             `json:"event_id"`
	OccurredAt time.Time          `json:"occurred_at"`

	// Position opaque cursor（时间线定位）
	Position string  `json:"position"`
	ThreadId *string `json:"thread_id,omitempty"`
}

// SearchHitActorKind defines model for SearchHit.ActorKind.
type SearchHitActorKind string

// Snapshot defines model for Snapshot.
type Snapshot struct {
	AlgorithmVersion int64 `json:"algorithm_version"`

	// Closures 收束清单（M3-2：pending 可接受 / accepted / rejected 各一条摘要）。
	Closures *[]ClosureSummary `json:"closures,omitempty"`

	// DevNotes 开发者模式回放条目（M3-1 持久化补全：事件支撑的 [dev] 内联信息，重启还原）。
	DevNotes *[]DevNote `json:"dev_notes,omitempty"`

	// DisplayName 房间名（room.created/room.renamed 投影产物）
	DisplayName string `json:"display_name"`

	// EvidenceRequests 证据需求单（M3-5：open/resolved/dismissed）。
	EvidenceRequests *[]EvidenceRequestView `json:"evidence_requests,omitempty"`

	// Graph 显式关系边（forked_from/responds_to/merged_into + relations 类型化边）。推断边属结构投影（M3），接入后标 inferred=true——双视图显式与推断区分。
	Graph []struct {
		From     string `json:"from"`
		Inferred bool   `json:"inferred"`
		Kind     string `json:"kind"`
		To       string `json:"to"`
	} `json:"graph"`

	// Participants 参与者视图（装配层注入：本地 owner + 引擎座位；非投影产物——ADR-0011 注记，不进 room_version/水位语义）。
	Participants      []ParticipantView `json:"participants"`
	ProjectionVersion int64             `json:"projection_version"`
	RoomId            string            `json:"room_id"`
	RoomVersion       int64             `json:"room_version"`

	// Roster 房间成员投影（room.created.agents + participant.admitted 链；null/缺 = 全部在席）。
	Roster *[]string `json:"roster,omitempty"`

	// Scorecard 记分卡（R-08/OQ-17：intent 全量投影，band + 未选理由 + 保送状态）。
	Scorecard []struct {
		Action           *string    `json:"action,omitempty"`
		Endorsed         bool       `json:"endorsed"`
		IntentId         string     `json:"intent_id"`
		OccurredAt       *time.Time `json:"occurred_at,omitempty"`
		ParticipantId    string     `json:"participant_id"`
		PublicRationale  *string    `json:"public_rationale,omitempty"`
		RoundId          *string    `json:"round_id,omitempty"`
		ScoreBand        string     `json:"score_band"`
		Selected         bool       `json:"selected"`
		Type             *string    `json:"type,omitempty"`
		UnselectedReason *string    `json:"unselected_reason,omitempty"`
	} `json:"scorecard"`

	// Tasks 任务清单（M3-3 tasklist，RFC-0012 OQ-A：带责任人 owner 的承诺追踪——确定性派生 + 人工门控裁定）。
	Tasks *[]TaskItem `json:"tasks,omitempty"`

	// Threads 线程投影（RFC-0004 生命周期状态 + fork 谱系 + 合并去向）。
	Threads []struct {
		Goal         *string              `json:"goal,omitempty"`
		MergedInto   *string              `json:"merged_into,omitempty"`
		MessageCount *int                 `json:"message_count,omitempty"`
		Parent       *string              `json:"parent,omitempty"`
		State        SnapshotThreadsState `json:"state"`
		ThreadId     string               `json:"thread_id"`
	} `json:"threads"`
	Timeline  []TimelineItem `json:"timeline"`
	Watermark string         `json:"watermark"`
}

// SnapshotThreadsState defines model for Snapshot.Threads.State.
type SnapshotThreadsState string

// TaskItem 任务清单项（M3-3 tasklist）：显式申报协议派生（mosaic-todo 围栏块）+ 人工门控裁定（task.resolved）。
type TaskItem struct {
	DeclaredAt  time.Time `json:"declared_at"`
	DeclaredSeq int64     `json:"declared_seq"`
	Note        *string   `json:"note,omitempty"`

	// Overdue pending 且 waves_since ≥ 2
	Overdue bool `json:"overdue"`

	// Owner 责任人（承诺者 participant_id——多 Agent 群聊对常见 tasklist 的必要增量）
	Owner      string     `json:"owner"`
	Resolution *string    `json:"resolution,omitempty"`
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	ResolvedBy *string    `json:"resolved_by,omitempty"`

	// SourceEventId 首次申报消息（provenance 跳转位）
	SourceEventId string         `json:"source_event_id"`
	Status        TaskItemStatus `json:"status"`

	// TaskId tsk_ 前缀（源事件哈希派生，确定性）
	TaskId string `json:"task_id"`

	// Text 申报事项文本（mosaic-todo 行，归一化后截断 120 字）
	Text string `json:"text"`

	// WavesSince 申报后经过的波数
	WavesSince int `json:"waves_since"`
}

// TaskItemStatus defines model for TaskItem.Status.
type TaskItemStatus string

// TimelineItem RFC-0012 群聊模型：Timeline = 消息族 + 暂停/恢复系统提醒（round.* 内部化，
// 不入用户可见时间线）。
type TimelineItem struct {
	ActorId    string    `json:"actor_id"`
	ActorKind  string    `json:"actor_kind"`
	Body       *string   `json:"body,omitempty"`
	EventId    string    `json:"event_id"`
	OccurredAt time.Time `json:"occurred_at"`
	Position   string    `json:"position"`
	ThreadId   *string   `json:"thread_id,omitempty"`
	Type       string    `json:"type"`
}

// ExecutableID defines model for ExecutableID.
type ExecutableID = string

// RoomID defines model for RoomID.
type RoomID = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// HarnessUnavailable defines model for HarnessUnavailable.
type HarnessUnavailable = Error

// Internal defines model for Internal.
type Internal = Error

// NotFound defines model for NotFound.
type NotFound = Error

// OriginRejected defines model for OriginRejected.
type OriginRejected = Error

// TooLarge defines model for TooLarge.
type TooLarge = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = Error

// GetHealthz200JSONResponseBodyStatus defines parameters for GetHealthz.
type GetHealthz200JSONResponseBodyStatus string

// AddHarnessExecutable201JSONResponseBodyStatus defines parameters for AddHarnessExecutable.
type AddHarnessExecutable201JSONResponseBodyStatus string

// DisableHarnessExecutable200JSONResponseBodyEnabled defines parameters for DisableHarnessExecutable.
type DisableHarnessExecutable200JSONResponseBodyEnabled bool

// EnableHarnessExecutable200JSONResponseBodyEnabled defines parameters for EnableHarnessExecutable.
type EnableHarnessExecutable200JSONResponseBodyEnabled bool

// SubscribeRoomEventsParams defines parameters for SubscribeRoomEvents.
type SubscribeRoomEventsParams struct {
	// Cursor opaque 游标（空 = 从头）；与 Last-Event-ID 同义，query 优先
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// SearchRoomMessagesParams defines parameters for SearchRoomMessages.
type SearchRoomMessagesParams struct {
	// Q 检索词（子串语义）
	Q string `form:"q" json:"q"`

	// Actor 按参与者过滤（participant_id）
	Actor *string `form:"actor,omitempty" json:"actor,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// AddHarnessExecutableJSONRequestBody defines body for AddHarnessExecutable for application/json ContentType.
type AddHarnessExecutableJSONRequestBody = ManualExecutableRequest

// UpdateHarnessExecutableJSONRequestBody defines body for UpdateHarnessExecutable for application/json ContentType.
type UpdateHarnessExecutableJSONRequestBody = RuntimeUpdateRequest

// CreateRoomJSONRequestBody defines body for CreateRoom for application/json ContentType.
type CreateRoomJSONRequestBody = RoomCommand

// SubmitRoomCommandJSONRequestBody defines body for SubmitRoomCommand for application/json ContentType.
type SubmitRoomCommandJSONRequestBody = RoomCommand

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealthz 存活探针
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// ListAgents 当前在席 Agent 座位（建房选择的候选集）+ 已发现未启用项
	// (GET /v1/agents)
	ListAgents(w http.ResponseWriter, r *http.Request)
	// ListHarnessExecutables 宿主扫描到的 agent CLI 注册表
	// (GET /v1/harness/executables)
	ListHarnessExecutables(w http.ResponseWriter, r *http.Request)
	// AddHarnessExecutable 手动登记 agent CLI（探测失败拒收）
	// (POST /v1/harness/executables)
	AddHarnessExecutable(w http.ResponseWriter, r *http.Request)
	// UpdateHarnessExecutable 更新运行参数（模型覆盖与思考强度；v1.48）
	// (PUT /v1/harness/executables/{id})
	UpdateHarnessExecutable(w http.ResponseWriter, r *http.Request, id ExecutableID)
	// DisableHarnessExecutable 禁用可执行项（座位随 resync 撤出）
	// (POST /v1/harness/executables/{id}/disable)
	DisableHarnessExecutable(w http.ResponseWriter, r *http.Request, id ExecutableID)
	// EnableHarnessExecutable 启用可执行项（登录门控；启用后 ≤10s 入座，无需重启）
	// (POST /v1/harness/executables/{id}/enable)
	EnableHarnessExecutable(w http.ResponseWriter, r *http.Request, id ExecutableID)
	// GetHarnessExecutableModels 模型候选与思考强度档位（v1.48）
	// (GET /v1/harness/executables/{id}/models)
	GetHarnessExecutableModels(w http.ResponseWriter, r *http.Request, id ExecutableID)
	// GetOwnerBootstrap 第一方客户端引导：返回 owner token（跨源门保护）
	// (GET /v1/owner/bootstrap)
	GetOwnerBootstrap(w http.ResponseWriter, r *http.Request)
	// ListRooms 房间列表（UI 重设计切片 1）
	// (GET /v1/rooms)
	ListRooms(w http.ResponseWriter, r *http.Request)
	// CreateRoom 创建房间（create_room 命令）
	// (POST /v1/rooms)
	CreateRoom(w http.ResponseWriter, r *http.Request)
	// SubmitRoomCommand 提交房间命令（post_message / pause_room / resume_room / rename_room 等）
	// (POST /v1/rooms/{room_id}/commands)
	SubmitRoomCommand(w http.ResponseWriter, r *http.Request, roomId RoomID)
	// SubscribeRoomEvents SSE 订阅房间事件流（opaque cursor 续传）
	// (GET /v1/rooms/{room_id}/events)
	SubscribeRoomEvents(w http.ResponseWriter, r *http.Request, roomId RoomID, params SubscribeRoomEventsParams)
	// GetRoomMemory 房间记忆视图（胶囊 + 编辑历史 + 容量水位）
	// (GET /v1/rooms/{room_id}/memory)
	GetRoomMemory(w http.ResponseWriter, r *http.Request, roomId RoomID)
	// SearchRoomMessages 房内消息全文检索（FTS5 trigram，按需平面）
	// (GET /v1/rooms/{room_id}/search)
	SearchRoomMessages(w http.ResponseWriter, r *http.Request, roomId RoomID, params SearchRoomMessagesParams)
	// GetRoomSnapshot 快照（版本 + 水位 + 投影/算法版本 + Timeline 投影 + 房间名/参与者视图）
	// (GET /v1/rooms/{room_id}/snapshot)
	GetRoomSnapshot(w http.ResponseWriter, r *http.Request, roomId RoomID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAgents operation middleware
func (siw *ServerInterfaceWrapper) ListAgents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHarnessExecutables operation middleware
func (siw *ServerInterfaceWrapper) ListHarnessExecutables(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHarnessExecutables(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddHarnessExecutable operation middleware
func (siw *ServerInterfaceWrapper) AddHarnessExecutable(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddHarnessExecutable(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateHarnessExecutable operation middleware
func (siw *ServerInterfaceWrapper) UpdateHarnessExecutable(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExecutableID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateHarnessExecutable(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DisableHarnessExecutable operation middleware
func (siw *ServerInterfaceWrapper) DisableHarnessExecutable(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExecutableID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DisableHarnessExecutable(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnableHarnessExecutable operation middleware
func (siw *ServerInterfaceWrapper) EnableHarnessExecutable(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExecutableID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnableHarnessExecutable(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHarnessExecutableModels operation middleware
func (siw *ServerInterfaceWrapper) GetHarnessExecutableModels(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExecutableID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHarnessExecutableModels(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOwnerBootstrap operation middleware
func (siw *ServerInterfaceWrapper) GetOwnerBootstrap(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOwnerBootstrap(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRooms operation middleware
func (siw *ServerInterfaceWrapper) ListRooms(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRooms(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRoom operation middleware
func (siw *ServerInterfaceWrapper) CreateRoom(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRoom(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitRoomCommand operation middleware
func (siw *ServerInterfaceWrapper) SubmitRoomCommand(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "room_id" -------------
	var roomId RoomID

	err = runtime.BindStyledParameterWithOptions("simple", "room_id", r.PathValue("room_id"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "room_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitRoomCommand(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubscribeRoomEvents operation middleware
func (siw *ServerInterfaceWrapper) SubscribeRoomEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "room_id" -------------
	var roomId RoomID

	err = runtime.BindStyledParameterWithOptions("simple", "room_id", r.PathValue("room_id"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "room_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeRoomEventsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubscribeRoomEvents(w, r, roomId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoomMemory operation middleware
func (siw *ServerInterfaceWrapper) GetRoomMemory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "room_id" -------------
	var roomId RoomID

	err = runtime.BindStyledParameterWithOptions("simple", "room_id", r.PathValue("room_id"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "room_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomMemory(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchRoomMessages operation middleware
func (siw *ServerInterfaceWrapper) SearchRoomMessages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "room_id" -------------
	var roomId RoomID

	err = runtime.BindStyledParameterWithOptions("simple", "room_id", r.PathValue("room_id"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "room_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchRoomMessagesParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "actor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "actor", r.URL.Query(), &params.Actor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "actor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "actor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchRoomMessages(w, r, roomId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoomSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetRoomSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "room_id" -------------
	var roomId RoomID

	err = runtime.BindStyledParameterWithOptions("simple", "room_id", r.PathValue("room_id"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "room_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomSnapshot(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/rooms", wrapper.ListRooms)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/rooms", wrapper.CreateRoom)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/rooms/{room_id}/commands", wrapper.SubmitRoomCommand)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/rooms/{room_id}/events", wrapper.SubscribeRoomEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/rooms/{room_id}/snapshot", wrapper.GetRoomSnapshot)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/rooms/{room_id}/memory", wrapper.GetRoomMemory)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/rooms/{room_id}/search", wrapper.SearchRoomMessages)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/agents", wrapper.ListAgents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/owner/bootstrap", wrapper.GetOwnerBootstrap)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/harness/executables", wrapper.ListHarnessExecutables)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/harness/executables", wrapper.AddHarnessExecutable)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/harness/executables/{id}/enable", wrapper.EnableHarnessExecutable)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/harness/executables/{id}/disable", wrapper.DisableHarnessExecutable)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/harness/executables/{id}", wrapper.UpdateHarnessExecutable)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/harness/executables/{id}/models", wrapper.GetHarnessExecutableModels)

	return m
}
