//go:build go1.22

// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for RoomCommandCommandKind.
const (
	CreateRoom  RoomCommandCommandKind = "create_room"
	PauseRoom   RoomCommandCommandKind = "pause_room"
	PostMessage RoomCommandCommandKind = "post_message"
	ResumeRoom  RoomCommandCommandKind = "resume_room"
)

// Valid indicates whether the value is a known member of the RoomCommandCommandKind enum.
func (e RoomCommandCommandKind) Valid() bool {
	switch e {
	case CreateRoom:
		return true
	case PauseRoom:
		return true
	case PostMessage:
		return true
	case ResumeRoom:
		return true
	default:
		return false
	}
}

// Defines values for GetHealthz200JSONResponseBodyStatus.
const (
	Ok GetHealthz200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the GetHealthz200JSONResponseBodyStatus enum.
func (e GetHealthz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for AddHarnessExecutable201JSONResponseBodyStatus.
const (
	Registered AddHarnessExecutable201JSONResponseBodyStatus = "registered"
)

// Valid indicates whether the value is a known member of the AddHarnessExecutable201JSONResponseBodyStatus enum.
func (e AddHarnessExecutable201JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Registered:
		return true
	default:
		return false
	}
}

// Defines values for DisableHarnessExecutable200JSONResponseBodyEnabled.
const (
	False DisableHarnessExecutable200JSONResponseBodyEnabled = false
)

// Valid indicates whether the value is a known member of the DisableHarnessExecutable200JSONResponseBodyEnabled enum.
func (e DisableHarnessExecutable200JSONResponseBodyEnabled) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// Defines values for EnableHarnessExecutable200JSONResponseBodyEnabled.
const (
	True EnableHarnessExecutable200JSONResponseBodyEnabled = true
)

// Valid indicates whether the value is a known member of the EnableHarnessExecutable200JSONResponseBodyEnabled enum.
func (e EnableHarnessExecutable200JSONResponseBodyEnabled) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// CommandResponse defines model for CommandResponse.
type CommandResponse struct {
	EventId     string `json:"event_id"`
	Replayed    bool   `json:"replayed"`
	RoomId      string `json:"room_id"`
	RoomVersion int64  `json:"room_version"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code 稳定错误码（transport 与 domain 映射）
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Executable defines model for Executable.
type Executable struct {
	Adapter string `json:"adapter"`

	// Digest sha256（版本固定门禁用）
	Digest       *string    `json:"digest,omitempty"`
	DiscoveredAt *time.Time `json:"discovered_at,omitempty"`

	// Distro WSL 运行面的发行版（native 为空）
	Distro  *string `json:"distro,omitempty"`
	Enabled bool    `json:"enabled"`

	// Id 注册表唯一 ID（adapter@runtime:path）
	Id string `json:"id"`

	// LoginState logged_in | logged_out | unknown
	LoginState *string `json:"login_state,omitempty"`
	Path       string  `json:"path"`

	// Runtime native | wsl
	Runtime string `json:"runtime"`

	// Source auto_scan | manual
	Source  *string `json:"source,omitempty"`
	Version *string `json:"version,omitempty"`
}

// ManualExecutableRequest defines model for ManualExecutableRequest.
type ManualExecutableRequest struct {
	Adapter string  `json:"adapter"`
	Distro  *string `json:"distro,omitempty"`
	Path    string  `json:"path"`
	Runtime string  `json:"runtime"`
	Version *string `json:"version,omitempty"`
}

// RoomCommand 命令信封（RFC-0001）。payload 按 command_kind 严格校验（未知字段拒绝）：
// create_room → CreateRoomPayload；post_message → PostMessagePayload；
// pause_room → PauseRoomPayload；resume_room → 空 payload。
type RoomCommand struct {
	CommandKind         RoomCommandCommandKind `json:"command_kind"`
	ExpectedRoomVersion int                    `json:"expected_room_version"`

	// IdempotencyKey UUIDv7（服务端按 tenant+key+kind 去重；同键异指纹 409）
	IdempotencyKey string                 `json:"idempotency_key"`
	IssuedAt       time.Time              `json:"issued_at"`
	Payload        map[string]interface{} `json:"payload"`
}

// RoomCommandCommandKind defines model for RoomCommand.CommandKind.
type RoomCommandCommandKind string

// Snapshot defines model for Snapshot.
type Snapshot struct {
	AlgorithmVersion  int64          `json:"algorithm_version"`
	ProjectionVersion int64          `json:"projection_version"`
	RoomId            string         `json:"room_id"`
	RoomVersion       int64          `json:"room_version"`
	Timeline          []TimelineItem `json:"timeline"`
	Watermark         string         `json:"watermark"`
}

// TimelineItem defines model for TimelineItem.
type TimelineItem struct {
	ActorId    string    `json:"actor_id"`
	ActorKind  string    `json:"actor_kind"`
	Body       *string   `json:"body,omitempty"`
	EventId    string    `json:"event_id"`
	OccurredAt time.Time `json:"occurred_at"`
	Position   string    `json:"position"`
	ThreadId   *string   `json:"thread_id,omitempty"`
	Type       string    `json:"type"`
}

// ExecutableID defines model for ExecutableID.
type ExecutableID = string

// RoomID defines model for RoomID.
type RoomID = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// HarnessUnavailable defines model for HarnessUnavailable.
type HarnessUnavailable = Error

// Internal defines model for Internal.
type Internal = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooLarge defines model for TooLarge.
type TooLarge = Error

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = Error

// GetHealthz200JSONResponseBodyStatus defines parameters for GetHealthz.
type GetHealthz200JSONResponseBodyStatus string

// AddHarnessExecutable201JSONResponseBodyStatus defines parameters for AddHarnessExecutable.
type AddHarnessExecutable201JSONResponseBodyStatus string

// DisableHarnessExecutable200JSONResponseBodyEnabled defines parameters for DisableHarnessExecutable.
type DisableHarnessExecutable200JSONResponseBodyEnabled bool

// EnableHarnessExecutable200JSONResponseBodyEnabled defines parameters for EnableHarnessExecutable.
type EnableHarnessExecutable200JSONResponseBodyEnabled bool

// SubscribeRoomEventsParams defines parameters for SubscribeRoomEvents.
type SubscribeRoomEventsParams struct {
	// Cursor opaque 游标（空 = 从头）；与 Last-Event-ID 同义，query 优先
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// AddHarnessExecutableJSONRequestBody defines body for AddHarnessExecutable for application/json ContentType.
type AddHarnessExecutableJSONRequestBody = ManualExecutableRequest

// CreateRoomJSONRequestBody defines body for CreateRoom for application/json ContentType.
type CreateRoomJSONRequestBody = RoomCommand

// SubmitRoomCommandJSONRequestBody defines body for SubmitRoomCommand for application/json ContentType.
type SubmitRoomCommandJSONRequestBody = RoomCommand

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealthz 存活探针
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// ListHarnessExecutables 宿主扫描到的 agent CLI 注册表
	// (GET /v1/harness/executables)
	ListHarnessExecutables(w http.ResponseWriter, r *http.Request)
	// AddHarnessExecutable 手动登记 agent CLI（探测失败拒收）
	// (POST /v1/harness/executables)
	AddHarnessExecutable(w http.ResponseWriter, r *http.Request)
	// DisableHarnessExecutable 禁用可执行项（座位随 resync 撤出）
	// (POST /v1/harness/executables/{id}/disable)
	DisableHarnessExecutable(w http.ResponseWriter, r *http.Request, id ExecutableID)
	// EnableHarnessExecutable 启用可执行项（登录门控；启用后 ≤10s 入座，无需重启）
	// (POST /v1/harness/executables/{id}/enable)
	EnableHarnessExecutable(w http.ResponseWriter, r *http.Request, id ExecutableID)
	// CreateRoom 创建房间（create_room 命令）
	// (POST /v1/rooms)
	CreateRoom(w http.ResponseWriter, r *http.Request)
	// SubmitRoomCommand 提交房间命令（post_message / pause_room / resume_room）
	// (POST /v1/rooms/{room_id}/commands)
	SubmitRoomCommand(w http.ResponseWriter, r *http.Request, roomId RoomID)
	// SubscribeRoomEvents SSE 订阅房间事件流（opaque cursor 续传）
	// (GET /v1/rooms/{room_id}/events)
	SubscribeRoomEvents(w http.ResponseWriter, r *http.Request, roomId RoomID, params SubscribeRoomEventsParams)
	// GetRoomSnapshot 快照四元组（版本 + 水位 + 投影/算法版本 + Timeline 投影）
	// (GET /v1/rooms/{room_id}/snapshot)
	GetRoomSnapshot(w http.ResponseWriter, r *http.Request, roomId RoomID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHarnessExecutables operation middleware
func (siw *ServerInterfaceWrapper) ListHarnessExecutables(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHarnessExecutables(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddHarnessExecutable operation middleware
func (siw *ServerInterfaceWrapper) AddHarnessExecutable(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddHarnessExecutable(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DisableHarnessExecutable operation middleware
func (siw *ServerInterfaceWrapper) DisableHarnessExecutable(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExecutableID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DisableHarnessExecutable(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnableHarnessExecutable operation middleware
func (siw *ServerInterfaceWrapper) EnableHarnessExecutable(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ExecutableID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnableHarnessExecutable(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRoom operation middleware
func (siw *ServerInterfaceWrapper) CreateRoom(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRoom(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitRoomCommand operation middleware
func (siw *ServerInterfaceWrapper) SubmitRoomCommand(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "room_id" -------------
	var roomId RoomID

	err = runtime.BindStyledParameterWithOptions("simple", "room_id", r.PathValue("room_id"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "room_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitRoomCommand(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubscribeRoomEvents operation middleware
func (siw *ServerInterfaceWrapper) SubscribeRoomEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "room_id" -------------
	var roomId RoomID

	err = runtime.BindStyledParameterWithOptions("simple", "room_id", r.PathValue("room_id"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "room_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeRoomEventsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubscribeRoomEvents(w, r, roomId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoomSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetRoomSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "room_id" -------------
	var roomId RoomID

	err = runtime.BindStyledParameterWithOptions("simple", "room_id", r.PathValue("room_id"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "room_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomSnapshot(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/rooms", wrapper.CreateRoom)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/rooms/{room_id}/commands", wrapper.SubmitRoomCommand)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/rooms/{room_id}/events", wrapper.SubscribeRoomEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/rooms/{room_id}/snapshot", wrapper.GetRoomSnapshot)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/harness/executables", wrapper.ListHarnessExecutables)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/harness/executables", wrapper.AddHarnessExecutable)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/harness/executables/{id}/enable", wrapper.EnableHarnessExecutable)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/harness/executables/{id}/disable", wrapper.DisableHarnessExecutable)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fp9UxPZmv8qp3rnPxPSAXwhVbd2Z9Q7w5besXzZlxE3HNIH6GvSnek+QblOqoARbYYEooJRQAa4KIwK",
	"0VExJs3wXa453clf/RW2Tp9O0kk6oixadav2v+4+b8/785zf0ze4iByLyxKSsMqFbnBxqMAYwkix305f",
	"R5EEhgNR1HuKvgtIjShiHIuyxIU449UmuZUqr26SuVwpPwZ6T1m6RjLPym9z5I+blp66dP4MMPX75sp4",
	"SV+pjN219CnOx4l0bRziYc7HSTCGuBAnCpyPU9CPCVFBAhfCSgL5ODUyjGKQHhsTpTNIGsLDXCjo4/Bo",
	"nK5RsSJKQ1wy6ePOy3KMEeixtyLLsfA+B8Qhxkiha//Hnn6Z9/d87f8B+v8W9l858hXXemiSbqfGZUlF",
	"tqS+gcJ59GMCqZi+RWQJI8l+hPF4VIxAKrLAX1Uqtxuug79S0CAX4v4lUNdCgI2qgdOKIivsqEa5l3Nv",
	"jZcTpXyaZDTj1bylawNQCCvseBAAojQCo6IQjsixGJQEEAB0PJJQVFlxXqJiTHRPRRJWRql6kj7upCwN",
	"RsXIF2DEnNKMpefk1u/m03EQAOTdhLk1VZnbNlK3zcI79t3StRGkqKIshSMOYZRuAcXiMkZSZLT22SH/",
	"O6hISFUvSXAEilFqu5+fEbK9V8oXa/5gLD2tTKbN3W1L14YZOeFEnR6H0F6J2hyMfn7yjKU0+WXVfJar",
	"zD0s53KWronO2SAAVAnG1WEZhwehGEWCQ9xfZPxnOSEJX4A4ba+SfW1o941Hq+biNjXrrQdkadPSNdsX",
	"JUoaJQUEQO3ZofKiLJ+ByhD6Yj63e6+8M1neuw2CZ8VvqOPJwmgYy3I4SslwqLokqYl4XFYwEs4iQYQX",
	"R+NfgMKTbHc/PQ1UVoulfAE0H2PpWqJOXDhGqQvT0GZTnqyGRDuinWTR47wT5einuCLHkYJFFvLQCJIw",
	"jayhG83hkQbHeBSOIvfggCxHEZTsUScme66kY47L0wmDshKDmAtxooSPdddDMTXhIaRwyaQ7sl92xfsa",
	"gU2buqi7UttOHvgrimBKAJNwK7venyOygFpTo7n5imwvMHczV2gQwwqUVCp3UMrPAEGOQVECxoMV8uIm",
	"S4stgoghVYXMtltTnptjm4T6/FaemuYzTjxZr+X7VkahAOMYKZ46E8QhJ/M1ikEdhp1Hj1m65kT6xQKV",
	"SnbTfDJuzm224VsQ1Yg8ghQkhCFusAABYuTHYgy1WYYVuZWG/7xwBpT3MuXVVOXRmrlwk8zeKa+mzCnN",
	"0jUJYnEEgVK+YP5WaEMOkqg82hiyKLQe6FkWOdL7NyUhUQZCtEZpc2BUHhKlsIoh9jCsqDw0hISwKIGf",
	"gPMsJzD4CSSkq5J8TfLakJ7l7WqMmNZTHLn8BK6pUa8dVTmhRDzWwQSWw2oEUupiUEpAz9Uu5/6wYduu",
	"W7W7Orm+aoVXVY2XKZ+1j68btKs6g4IgUoJh9JzLwgdhVEW+TzL6qsEdSOIHF0tbiXjJgdbGTijfl/em",
	"oubObqm4XtpbJS9oADv/55N+nueDlj71fmwiDkejMhSAkZoCTp0ZvipKAijlHxsrurGyWnmasnTNWHpq",
	"/vqYbGWN7TfG9F2z+MjSpyx9oU+KKAhiFKaRGfzj1l1w0n6n5J5je1v6YlxWcdiJa/akc7KKz7L3+qw+",
	"KQ4Tqmurc/S1cScFqYmYa4r5WwE4PLwfm+iTuGbNu5mi70hKxOxgWyebrnERSF9rdNhJpnakSzOuwHI9",
	"jiI0DTdnvJgoiTF6Gt+a7Hycu/S9ikZbnfDSpd5TI8dt2TtlH1USRhKU8JGraPSIrScyU6zcTlv6Ismk",
	"KnPbRJ9gVTfo5ntYYHJdiuh9CPoHr9w4kfTXnruT/uO1l66k//KJHjhwpeFL9TnYmfzKKxKIqpr4xDDv",
	"KM3lJW2yXIMC20m7VZxuouqneXnWBadw9kiV0SFZEfHwp9UxtgXSzeld59MWHmo95eOo7KOiZIcpEaOY",
	"ul9RetFZ0ItRjEvWtoSKAkfp+zWIkRKDytX9g5vrut6oqPoenoLyeUjdxYmXAhuoblViBMtKO6GywWps",
	"aBmm1wLPgQ/WzHIkklA+teyJy6qIvdOGj8PDCoKCc54soe8HudDl2jwpEY1ySV/Luis1De6nrNrhDcW2",
	"vcZXF2CDuBrZ9KhVaViQBj0KubOyCsUIKOWflgoFp6BcegG+u3jxHCCP75iFJ5aufX3qPM1Sxy194fs4",
	"kr4+1wu6OoK0wmMTK4/WjEc/k81xY3a2vPfC0lMyjIt+WkIPIalPMud+NbQM+FYGtehZ/uOdOZ8yNlfJ",
	"8rSlL5YK06XiTjV5AHPhprNhIVMqpo0HOQDjYoAarz+uyFiOyFE6Cfz7he//Ai7YDsNSaJ/UJ5HdNWNs",
	"3Cw8MR79amdFPyDpeXNu09DeMv7Ke4vm5rSlpyrFB+Xt9VJxkiwumzM5c/EOyTy3dC3YebyD7+A7gqHj",
	"3Z28nV0X5WsSUoBZ2ABUAGT3HplKG9mV8vZ6OTfeJwFg6Rqbg+WrSALk5TI42wmM7Wlz/mFl9Z2lp8rb",
	"q0S7C0aCHUEemA+L5e0XVbL9gNx6aD7LmRPvym83jUKmkt2k8lbEIVECZP01u8Ab2R2yN1lZLRoPcn0c",
	"oxoMyyoGRwCDR8xnOTL79z6OZqH8E0C9hoqqtjultPxk3Hg5Ady325DXvbY7eDTQzXeBcm6r9G6qvDFO",
	"MjfZLuRemhTmXMSzumb3Xin/S+VhpnqV7w52MeGVc8XyzqSR3QHHjqqWrl24cBoY2RVG3renLwIKUcxm",
	"ye5Lci9d39bI542V29TQ5Dj8MYEA2cqaz5+U8r9b+gJd8ke2vPF3YzlDJnfIrcnKz5tm8Z6xTHFSs7hV",
	"0lfIzK/GyluyuFzSV1z1FjjH1w+htJS31yoPJi19oR+j6zhgO55fxQqCsX5LT5H8hrGiE30W9ItCCPQl",
	"eL4rwsA/+xn1gyOg315VHaUu6BoTIIbVodN03n+I6Jptv84ku+YCwLi/ZRb2KrfT5b1lqr/+M1DFfnuF",
	"v/dUP7UEWoVo90H/vzIC/tRv6VOl4ozx4nVpN83YtvRUKZ825l8b228qt9PG3B/O9v2CAgdxRyJO41+/",
	"fUlbfm6MjZP8Bt02uwJE4f3YOKOilE+XVx+T2TtMhzXnJbN3QL+C1FEpEq5Grn5AJt+STJp5spHdoaeR",
	"7TVDe0tXFObKb16QvWfm5IYxvkbW0+/HJthU82WRLE+XN8ZbXZypQQ1Ui0ks4iiqBy1ajFJf5FxlPsd3",
	"BDt4O/DHkQTjIhfiuuxPrJy3s1BgGMEoHv4bfR5Cdl6gSco2/V6BC3HfIvydM6UJku7k+U9CnRrTn4oh",
	"TjiVsKRiLsTJVznfPvnAWeQd1b0wSbL1wHhdtPdRE7EYVEa5EMc+GjNrlbuaPRQYCQYcHDWAajc6ta1M",
	"zogqdmDg067phyqfJjo+qkyqE9NaJDVJ0r39R4mzBjpo2fLqJt3/KN/VjqCaHAIeaHmTMhi0PfXMmJ0l",
	"2guayeAQkjA4eaYX1E51KhEPXXwtCC2qcHoxSMXfOIXSoUCj7a78yWSyufmTbLGF4KH6ioKGRBVTDOsw",
	"fYa8/Z1lYirubp5vJ5C6el1tKbok+BEWUcPU7QVH91/gCXcfmv0ZU9Pkl03Gdt3yaAKYWTPeTJP1l+XX",
	"j43pu8bcThXEbhMuAjdEIRkQRLWGb3oa7Ck2wcto3c3Ry96c1acEGpqnySuHG33qoKRjcg6E0wpR1o3z",
	"o+zwQ6iat0XaWC6zyO79FV5rLB2ahTACyGzOmNqgKC8tXzVS2CjtpisLs4Alf2DcXSe3Cx9lIkwA7S3k",
	"tPTPaCCs5/3l7YNkcge1j26+5/P3zRjcXuXUgSwfFsnuvF3n5xj9TmvvkHJqJtdqsezMSnbTmNmwYTl7",
	"TmYG/GNqPcirgEw+JoUNS08Z2ZXK0ljldppkcm57pvWo2t5q6/jqJ6dfdB3G4tU+uhsWbUJD2yCavAdo",
	"yfHBE4PHBjqR/3gkCP3HB7oEfw/qHvQHYedAV6Rb6OH5YAMYF+I6+c5jfv6Ev4u/yPeEuvgQz3fwPP8D",
	"14AKCqJKm3th5/cP8/nzUn6slH/K+syuLud+FuNGzj+qhOAPzVibe69enmXfYsls1szcYr/dsN8nyOKy",
	"fYWaOmiNwPfsv6T2i8gXLioavUhbJMUCU6ula+5+AhNOi3MEbjjoYjLg2PEH/OVCYiAmYrcRfGp8d35L",
	"YpH9AP7GiKu3FEI3uBEYTXj5YUPjoY0b9hzQDbs+7IZBbzdUEFTZzWRhgowv2T44zQy5oWnyIaYamytt",
	"2Oo+IFud+0aXoAdbUBAUpKpICGOZC12+UsV6uVJ+zHi0auxoxnjODrBRW6fMUByG0HWMqM35OEydAYfr",
	"cDCHRnCYD3534r/++wfHYuLRUfsQCtMmk/8ft/aLWwcrLv4JAp0xmykV1lmgq0Y2raE1GgCuDmgAuDqP",
	"H4qBDLJyoShNmrJx01K+UJnfM96MAw+48f3YBIM9GepKMcka0gds4K8RErR0jcGFDKXrk8ikxuBMkpkp",
	"7+2Sd68sPVXtKjg9SjK5RArzFNSbXDN2tPLrd+WxyQCbza5/+4N8fRQiprgmIJlngMUmS58imRnj/pbx",
	"ZpziplUA0MgUjKUxWnmJAmDkGtr9GiZYRfhasgWV3YBdYJ1mgj1ovvA1a8IBlJmoaan4WwH8CZSKMzbC",
	"SiVJ/ylqEDUgmZStkdSPCaSMgpL+gExq1b9v7W/1X2SZyjh3gGm+C+x/O2mxjsaw4fEDbSOTDhr7ZpxB",
	"7geNBA2eU4fLmfe4z3CEyngHVSy6vbeornZvOySWarDWFv4/lQufKUDXiPOKzLZ5H/Ai/xFaqv3v2lTG",
	"2ceSxUUy+bNZvFn7WQwcAaxNQB9+mSe7LwPmdtZ4NV8brvZvnWGmPLo3UkaqMm9kkfXQmhpotYYi++0h",
	"oUS5EDeMcTwUCDQ212hr9H8HAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
