/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针 */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建房间（create_room 命令） */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{room_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交房间命令（post_message / pause_room / resume_room） */
        post: operations["submitRoomCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{room_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE 订阅房间事件流（opaque cursor 续传）
         * @description 响应为长流 `text/event-stream`。游标语义：`?cursor=` 或 `Last-Event-ID`（重连）；
         *     先订阅后追平，position 去重兜底；慢消费者/追平失败发 `resync_required` 具名事件
         *     （data 含 reason）后断流，客户端携最后 id 重连或走快照。
         */
        get: operations["subscribeRoomEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{room_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 快照四元组（版本 + 水位 + 投影/算法版本 + Timeline 投影） */
        get: operations["getRoomSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 第一方客户端引导：返回 owner token（跨源门保护）
         * @description 仅在配置了 OwnerToken 的装配上注册。响应含写端点所需的 X-Owner-Token 值。
         *     读取本身过跨源门：Origin 存在且非信任源（回环/壳源）→ 403——DNS rebinding
         *     页面同源化后也读不到 token（写通道另由 Origin 门 + token 双重把守）。
         *     无 Origin 的本机客户端（curl/同源 GET）可达——同用户本机进程本就等效 owner。
         */
        get: operations["getOwnerBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/harness/executables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 宿主扫描到的 agent CLI 注册表 */
        get: operations["listHarnessExecutables"];
        put?: never;
        /** 手动登记 agent CLI（探测失败拒收） */
        post: operations["addHarnessExecutable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/harness/executables/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 启用可执行项（登录门控；启用后 ≤10s 入座，无需重启） */
        post: operations["enableHarnessExecutable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/harness/executables/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 禁用可执行项（座位随 resync 撤出） */
        post: operations["disableHarnessExecutable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 命令信封（RFC-0001）。payload 按 command_kind 严格校验（未知字段拒绝）：
         *     create_room → CreateRoomPayload；post_message → PostMessagePayload；
         *     pause_room → PauseRoomPayload；resume_room → 空 payload；
         *     set_policy → PolicyParams（RFC-0003 §3.1.7；变更只在 round 边界生效）。
         */
        RoomCommand: {
            /** @enum {string} */
            command_kind: "create_room" | "post_message" | "pause_room" | "resume_room" | "set_policy";
            expected_room_version: number;
            /** @description UUIDv7（服务端按 tenant+key+kind 去重；同键异指纹 409） */
            idempotency_key: string;
            /** Format: date-time */
            issued_at: string;
            payload: Record<string, never>;
        };
        CreateRoomPayload: {
            display_name?: string;
        };
        /** @description 字段集与 events/message.posted.schema.json 对齐（M2 定稿）；relations 项不收 provenance（系统固化 explicit）。 */
        PostMessagePayload: {
            body: string;
            reply_to?: null | string;
            addressed_to?: string[];
            relations?: components["schemas"]["TypedRelationInput"][];
            thread_id?: null | string;
        };
        TypedRelationInput: {
            target_event_id: string;
            /** @enum {string} */
            kind: "supports" | "challenges" | "extends" | "questions" | "evidence_for" | "supersedes" | "analogy" | "relates";
        };
        PauseRoomPayload: {
            reason?: string;
        };
        /** @description 策略参数束（RFC-0003 §3.1.7；set_policy 命令体与 policy.changed 事件 payload 同构）。reveal 三策略自 B2 起全部可执行（simultaneous=冻结水位统一揭示；independent_then_cross=独立首轮+cross 子轮）。 */
        PolicyParams: {
            /** @enum {string} */
            mode: "roundtable" | "open_floor" | "deep_dive" | "review" | "decision";
            max_speakers: number;
            lambda: number;
            weights: {
                relevance: number;
                novelty: number;
                diversity: number;
                urgency: number;
                direct_address: number;
                floor_share: number;
                repetition: number;
            };
            intent_window: string;
            /** Format: int64 */
            response_cap: number;
            /** @enum {string} */
            reveal_strategy: "sequential" | "simultaneous" | "independent_then_cross";
            /** @description cross 子轮数（Roundtable 默认 1；仅 independent_then_cross 消费） */
            rebuttals: number;
        };
        CommandResponse: {
            room_id: string;
            event_id: string;
            /** Format: int64 */
            room_version: number;
            replayed: boolean;
        };
        Error: {
            error: {
                /** @description 稳定错误码（transport 与 domain 映射） */
                code: string;
                message: string;
            };
        };
        /** @description 对外事件视图（RFC-0001 P0：无 seq/tenant_id，opaque position 替代）；payload 的事件族 Schema 见 api/room-protocol/events/。 */
        EventView: {
            event_id: string;
            room_id: string;
            thread_id?: null | string;
            type: string;
            schema_version: number;
            /** Format: date-time */
            occurred_at: string;
            actor: {
                participant_id: string;
                /** @enum {string} */
                kind: "human" | "agent" | "system";
            };
            causation_id?: null | string;
            correlation_id?: null | string;
            visibility: {
                /** @enum {string} */
                kind: "public" | "participants" | "moderators" | "system";
                participants?: string[];
            };
            payload: Record<string, never>;
            /** @description opaque cursor（续传位点） */
            position: string;
        };
        Snapshot: {
            room_id: string;
            /** Format: int64 */
            room_version: number;
            watermark: string;
            /** Format: int64 */
            projection_version: number;
            /** Format: int64 */
            algorithm_version: number;
            /** @description 当前策略区（记分卡透明 OQ-17——权重/模式参数对成员可见、版本化）。 */
            policy: {
                policy_version: string;
                mode?: string;
                max_speakers?: number;
                lambda?: number;
                weights?: Record<string, never>;
                intent_window?: string;
                /** Format: int64 */
                response_cap?: number;
                reveal_strategy?: string;
            };
            timeline: components["schemas"]["TimelineItem"][];
        };
        TimelineItem: {
            position: string;
            event_id: string;
            type: string;
            actor_id: string;
            actor_kind: string;
            body?: string;
            thread_id?: null | string;
            /** Format: date-time */
            occurred_at: string;
        };
        Executable: {
            /** @description 注册表唯一 ID（adapter@runtime:path） */
            id: string;
            adapter: string;
            /** @description native | wsl */
            runtime: string;
            /** @description WSL 运行面的发行版（native 为空） */
            distro?: string;
            path: string;
            version?: string;
            /** @description sha256（版本固定门禁用） */
            digest?: string;
            /** @description logged_in | logged_out | unknown */
            login_state?: string;
            /** @description auto_scan | manual */
            source?: string;
            /** Format: date-time */
            discovered_at?: string;
            enabled: boolean;
        };
        ManualExecutableRequest: {
            adapter: string;
            runtime: string;
            distro?: string;
            path: string;
            version?: string;
        };
    };
    responses: {
        /** @description 请求不合法（bad_request / invalid_command / bad_cursor / bad_limit / invalid_entry） */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 跨源拒绝（origin_rejected——本地 owner API） */
        OriginRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 缺少或错误的 X-Owner-Token（owner_token_required） */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 版本冲突 / 幂等键指纹冲突（version_conflict / idempotency_conflict） */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 房间或条目不存在（room_not_found / not_found） */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求体超过 1MiB（body_too_large） */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Content-Type 须为 application/json（unsupported_media_type） */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 宿主注册表未配置（harness_unavailable） */
        HarnessUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 服务端错误（internal / snapshot_failed） */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        RoomID: string;
        /** @description 注册表唯一 ID（含路径，URL 编码传递） */
        ExecutableID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "command_kind": "create_room",
                 *       "expected_room_version": 0,
                 *       "idempotency_key": "018f6b2e-7c1a-7b3d-9e4f-1a2b3c4d9001",
                 *       "issued_at": "2026-08-30T09:30:00.000Z",
                 *       "payload": {
                 *         "display_name": "第一个房间"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["RoomCommand"];
            };
        };
        responses: {
            /** @description 命令受理（含幂等回放） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    submitRoomCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomCommand"];
            };
        };
        responses: {
            /** @description 命令受理（含幂等回放） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    subscribeRoomEvents: {
        parameters: {
            query?: {
                /** @description opaque 游标（空 = 从头）；与 Last-Event-ID 同义，query 优先 */
                cursor?: string;
            };
            header?: never;
            path: {
                room_id: components["parameters"]["RoomID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 事件流（SSE） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getRoomSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 快照 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    getOwnerBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            403: components["responses"]["OriginRejected"];
            /** @description 本装配未启用 owner token（owner_token_disabled） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listHarnessExecutables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 注册表列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        executables: components["schemas"]["Executable"][];
                    };
                };
            };
            503: components["responses"]["HarnessUnavailable"];
        };
    };
    addHarnessExecutable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualExecutableRequest"];
            };
        };
        responses: {
            /** @description 已登记 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "registered";
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            503: components["responses"]["HarnessUnavailable"];
        };
    };
    enableHarnessExecutable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 注册表唯一 ID（含路径，URL 编码传递） */
                id: components["parameters"]["ExecutableID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已启用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        /** @constant */
                        enabled: true;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description login_required（未登录不可启用） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["HarnessUnavailable"];
        };
    };
    disableHarnessExecutable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 注册表唯一 ID（含路径，URL 编码传递） */
                id: components["parameters"]["ExecutableID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已禁用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        /** @constant */
                        enabled: false;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["HarnessUnavailable"];
        };
    };
}
