/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针 */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 房间列表（UI 重设计切片 1）
         * @description 全量房间摘要，按 last_event_at 倒序（无事件的房间 last_event_at = created_at）。
         *     只读端点：与既有读面一致，不设 owner token 门（见本文档顶部形态约束）。
         */
        get: operations["listRooms"];
        put?: never;
        /** 创建房间（create_room 命令） */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{room_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交房间命令（post_message / pause_room / resume_room / rename_room 等） */
        post: operations["submitRoomCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{room_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE 订阅房间事件流（opaque cursor 续传）
         * @description 响应为长流 `text/event-stream`。游标语义：`?cursor=` 或 `Last-Event-ID`（重连）；
         *     先订阅后追平，position 去重兜底；慢消费者/追平失败发 `resync_required` 具名事件
         *     （data 含 reason）后断流，客户端携最后 id 重连或走快照。
         */
        get: operations["subscribeRoomEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{room_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 快照（版本 + 水位 + 投影/算法版本 + Timeline 投影 + 房间名/参与者视图） */
        get: operations["getRoomSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前在席 Agent 座位（建房选择的候选集）+ 已发现未启用项
         * @description 引擎座位快照（已启用的真实适配器 + echo 基线）。participant_id 即建房
         *     create_room.payload.agents 项与 invite_agent 目标。座位随 harness 启停
         *     动态变化（10s resync）。disabled 为已发现但未启用的可执行项（v1.24：
         *     选人页如实展示"还有谁未启用"，指路设置）——仅有 adapter/channel/version，
         *     无 participant_id（未入席）。
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 第一方客户端引导：返回 owner token（跨源门保护）
         * @description 仅在配置了 OwnerToken 的装配上注册。响应含写端点所需的 X-Owner-Token 值。
         *     读取本身过跨源门：Origin 存在且非信任源（回环/壳源）→ 403——DNS rebinding
         *     页面同源化后也读不到 token（写通道另由 Origin 门 + token 双重把守）。
         *     无 Origin 的本机客户端（curl/同源 GET）可达——同用户本机进程本就等效 owner。
         */
        get: operations["getOwnerBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/harness/executables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 宿主扫描到的 agent CLI 注册表 */
        get: operations["listHarnessExecutables"];
        put?: never;
        /** 手动登记 agent CLI（探测失败拒收） */
        post: operations["addHarnessExecutable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/harness/executables/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 启用可执行项（登录门控；启用后 ≤10s 入座，无需重启） */
        post: operations["enableHarnessExecutable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/harness/executables/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 禁用可执行项（座位随 resync 撤出） */
        post: operations["disableHarnessExecutable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 命令信封（RFC-0001）。payload 按 command_kind 严格校验（未知字段拒绝）：
         *     create_room → CreateRoomPayload；post_message → PostMessagePayload；
         *     pause_room → PauseRoomPayload；resume_room → 空 payload；
         *     rename_room → RenameRoomPayload（UI 重设计切片 1；room.renamed 事件）；
         *     set_policy → PolicyParams（RFC-0003 §3.1.7；变更只在 round 边界生效）；
         *     endorse_intent → EndorseIntentPayload（OQ-17 人类保送，effect=grant）；
         *     invite_agent → {participant_id}（RFC-0001 Membership：participant.admitted 拉人）；
         *     fork/pause/resume/close/reopen/merge_thread → ThreadLifecyclePayload（RFC-0004 线程生命周期，
         *     状态机转移校验；merge 在个人版单 owner 形态下为直接命令=确认权）。
         */
        RoomCommand: {
            /** @enum {string} */
            command_kind: "create_room" | "post_message" | "pause_room" | "resume_room" | "rename_room" | "set_policy" | "endorse_intent" | "invite_agent" | "fork_thread" | "pause_thread" | "resume_thread" | "close_thread" | "reopen_thread" | "merge_thread";
            expected_room_version: number;
            /** @description UUIDv7（服务端按 tenant+key+kind 去重；同键异指纹 409） */
            idempotency_key: string;
            /** Format: date-time */
            issued_at: string;
            payload: Record<string, never>;
        };
        CreateRoomPayload: {
            display_name?: string;
            /** @description 入房 Agent（participant ID，见 GET /v1/agents）。缺省/空 = 全部在席；非空 = 恰好所选（后续可 invite_agent 拉人）。 */
            agents?: string[];
        };
        /** @description 房间改名载荷（room.renamed 事件载荷同构）；改名不接受置空/纯空白。 */
        RenameRoomPayload: {
            display_name: string;
        };
        RoomList: {
            rooms: components["schemas"]["RoomSummary"][];
        };
        RoomSummary: {
            room_id: string;
            /** @description 最新 room.created/room.renamed 投影 */
            display_name: string;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description 该房间最新事件时间（无事件则等于 created_at）；列表按此倒序
             */
            last_event_at: string;
            /** @description 最新生命周期事件为 room.paused */
            paused: boolean;
            /**
             * Format: int64
             * @description message.posted 类事件数
             */
            message_count: number;
        };
        /** @description 字段集与 events/message.posted.schema.json 对齐（M2 定稿）；relations 项不收 provenance（系统固化 explicit）。 */
        PostMessagePayload: {
            body: string;
            reply_to?: null | string;
            addressed_to?: string[];
            relations?: components["schemas"]["TypedRelationInput"][];
            thread_id?: null | string;
        };
        TypedRelationInput: {
            target_event_id: string;
            /** @enum {string} */
            kind: "supports" | "challenges" | "extends" | "questions" | "evidence_for" | "supersedes" | "analogy" | "relates";
        };
        PauseRoomPayload: {
            reason?: string;
        };
        /** @description 线程生命周期命令载荷（RFC-0004）。fork_thread 必填 source_event_id+goal；其余必填 thread_id；merge 另必填 merged_into。 */
        ThreadLifecyclePayload: {
            thread_id?: string;
            source_event_id?: string;
            goal?: string;
            participants?: string[];
            merged_into?: string;
            reason?: string;
        };
        /** @description 人类保送（RFC-0003 §3.1.11 / OQ-17）。effect=grant 直接授予 Floor（默认）；boost 随 Policy 加权参数定稿开放。不绕过预算/硬资格/安全；对全体可见。 */
        EndorseIntentPayload: {
            intent_id: string;
            /** @enum {string} */
            effect: "grant";
        };
        /** @description 策略参数束（RFC-0003 §3.1.7；set_policy 命令体与 policy.changed 事件 payload 同构）。reveal 三策略自 B2 起全部可执行（simultaneous=冻结水位统一揭示；independent_then_cross=独立首轮+cross 子轮）。auto_rounds 为自动续聊轮数上限（0=关；计划 v1.26）。 */
        PolicyParams: {
            /** @enum {string} */
            mode: "roundtable" | "open_floor" | "deep_dive" | "review" | "decision";
            max_speakers: number;
            lambda: number;
            weights: {
                relevance: number;
                novelty: number;
                diversity: number;
                urgency: number;
                direct_address: number;
                floor_share: number;
                repetition: number;
            };
            intent_window: string;
            /** Format: int64 */
            response_cap: number;
            /** @enum {string} */
            reveal_strategy: "sequential" | "simultaneous" | "independent_then_cross";
            /** @description cross 子轮数（Roundtable 默认 1；仅 independent_then_cross 消费） */
            rebuttals: number;
            /** @description 自动续聊轮数上限（0=关；Open Floor 默认 3 / Deep Dive 2；停止条件=轮数上限/静默轮/预算 100% 硬停） */
            auto_rounds: number;
        };
        CommandResponse: {
            room_id: string;
            event_id: string;
            /** Format: int64 */
            room_version: number;
            replayed: boolean;
        };
        Error: {
            error: {
                /** @description 稳定错误码（transport 与 domain 映射） */
                code: string;
                message: string;
            };
        };
        /** @description 对外事件视图（RFC-0001 P0：无 seq/tenant_id，opaque position 替代）；payload 的事件族 Schema 见 api/room-protocol/events/。 */
        EventView: {
            event_id: string;
            room_id: string;
            thread_id?: null | string;
            type: string;
            schema_version: number;
            /** Format: date-time */
            occurred_at: string;
            actor: {
                participant_id: string;
                /** @enum {string} */
                kind: "human" | "agent" | "system";
            };
            causation_id?: null | string;
            correlation_id?: null | string;
            visibility: {
                /** @enum {string} */
                kind: "public" | "participants" | "moderators" | "system";
                participants?: string[];
            };
            payload: Record<string, never>;
            /** @description opaque cursor（续传位点） */
            position: string;
        };
        Snapshot: {
            room_id: string;
            /** Format: int64 */
            room_version: number;
            watermark: string;
            /** Format: int64 */
            projection_version: number;
            /** Format: int64 */
            algorithm_version: number;
            /** @description 房间名（room.created/room.renamed 投影产物） */
            display_name: string;
            /** @description 参与者视图（装配层注入：本地 owner + 引擎座位；非投影产物——ADR-0011 注记，不进 room_version/水位语义）。 */
            participants: components["schemas"]["ParticipantView"][];
            /** @description 当前策略区（记分卡透明 OQ-17——权重/模式参数对成员可见、版本化）。 */
            policy: {
                policy_version: string;
                mode?: string;
                max_speakers?: number;
                lambda?: number;
                weights?: Record<string, never>;
                intent_window?: string;
                /** Format: int64 */
                response_cap?: number;
                reveal_strategy?: string;
                /** @description 自动续聊轮数上限（0=关；Open Floor 默认 3 / Deep Dive 2；RFC §3.1.7，计划 v1.26） */
                auto_rounds?: number;
            };
            /** @description 房间成员投影（room.created.agents + participant.admitted 链；null/缺 = 全部在席）。 */
            roster?: string[];
            /** @description 线程投影（RFC-0004 生命周期状态 + fork 谱系 + 合并去向）。 */
            threads: {
                thread_id: string;
                /** @enum {string} */
                state: "active" | "paused" | "closed" | "merged";
                parent?: string;
                goal?: string;
                merged_into?: string;
                message_count?: number;
            }[];
            /** @description 显式关系边（forked_from/responds_to/merged_into + relations 类型化边）。推断边属结构投影（M3），接入后标 inferred=true——双视图显式与推断区分。 */
            graph: {
                kind: string;
                from: string;
                to: string;
                inferred: boolean;
            }[];
            /** @description 记分卡（R-08/OQ-17：intent 全量投影，band + 未选理由 + 保送状态）。 */
            scorecard: {
                intent_id: string;
                participant_id: string;
                type?: string;
                action?: string;
                score_band: string;
                selected: boolean;
                endorsed: boolean;
                public_rationale?: string;
                unselected_reason?: string;
                round_id?: string;
                /** Format: date-time */
                occurred_at?: string;
            }[];
            timeline: components["schemas"]["TimelineItem"][];
        };
        ParticipantView: {
            participant_id: string;
            /** @enum {string} */
            kind: "human" | "agent" | "system";
            /** @description 引擎已知名字（Owner/Echo/Codex/Kimi 等） */
            display_name: string;
            /** @description agent 座位的适配器名（human 无此键） */
            adapter?: string;
            /** @description harness 渠道标签（cli/app:codex-desktop 等；无则省略） */
            channel?: string;
            /** @description seated（在座；离座语义随 UI 重设计后续切片定稿） */
            seat_status: string;
        };
        /**
         * @description v1.25 起 Timeline 含系统事件（round.opened / round.closed / room.paused /
         *     room.started）——轮次提醒随快照持久化（此前仅 SSE 瞬态，切房间即失）。
         *     outcome 仅 round.closed 携带（结果标签，客户端映射用户语言）；
         *     auto_index 仅 round.opened 携带（>0 = 自动续聊轮，v1.27）。
         */
        TimelineItem: {
            position: string;
            event_id: string;
            type: string;
            actor_id: string;
            actor_kind: string;
            body?: string;
            outcome?: string;
            /** @description 自动续聊轮序（1..auto_rounds；缺省 = 人类消息驱动轮） */
            auto_index?: number;
            thread_id?: null | string;
            /** Format: date-time */
            occurred_at: string;
        };
        Executable: {
            /** @description 注册表唯一 ID（adapter@runtime:path） */
            id: string;
            adapter: string;
            /** @description native | wsl */
            runtime: string;
            /** @description WSL 运行面的发行版（native 为空） */
            distro?: string;
            path: string;
            version?: string;
            /** @description sha256（版本固定门禁用） */
            digest?: string;
            /** @description logged_in | logged_out | unknown */
            login_state?: string;
            /** @description auto_scan | manual */
            source?: string;
            /** @description 实例渠道（ADR-0012）：cli | app:codex-desktop | app:kimi-work */
            channel?: string;
            /** @description 家族裁定优先级（数值小者优先；列表已按 adapter→priority→path 排序） */
            priority?: number;
            /** Format: date-time */
            discovered_at?: string;
            enabled: boolean;
        };
        ManualExecutableRequest: {
            adapter: string;
            runtime: string;
            distro?: string;
            path: string;
            version?: string;
            /** @description 可选渠道覆盖（cli 或 app:<小写>），空值按 cli */
            channel?: string;
        };
    };
    responses: {
        /** @description 请求不合法（bad_request / invalid_command / bad_cursor / bad_limit / invalid_entry） */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 跨源拒绝（origin_rejected——本地 owner API） */
        OriginRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 缺少或错误的 X-Owner-Token（owner_token_required） */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 版本冲突 / 幂等键指纹冲突（version_conflict / idempotency_conflict） */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 房间或条目不存在（room_not_found / not_found） */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求体超过 1MiB（body_too_large） */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Content-Type 须为 application/json（unsupported_media_type） */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 宿主注册表未配置（harness_unavailable） */
        HarnessUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 服务端错误（internal / snapshot_failed） */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        RoomID: string;
        /** @description 注册表唯一 ID（含路径，URL 编码传递） */
        ExecutableID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    listRooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 房间列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomList"];
                };
            };
            500: components["responses"]["Internal"];
        };
    };
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "command_kind": "create_room",
                 *       "expected_room_version": 0,
                 *       "idempotency_key": "018f6b2e-7c1a-7b3d-9e4f-1a2b3c4d9001",
                 *       "issued_at": "2026-08-30T09:30:00.000Z",
                 *       "payload": {
                 *         "display_name": "第一个房间"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["RoomCommand"];
            };
        };
        responses: {
            /** @description 命令受理（含幂等回放） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    submitRoomCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomCommand"];
            };
        };
        responses: {
            /** @description 命令受理（含幂等回放） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    subscribeRoomEvents: {
        parameters: {
            query?: {
                /** @description opaque 游标（空 = 从头）；与 Last-Event-ID 同义，query 优先 */
                cursor?: string;
            };
            header?: never;
            path: {
                room_id: components["parameters"]["RoomID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 事件流（SSE） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getRoomSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 快照 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 座位列表 + 未启用项 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agents: {
                            participant_id: string;
                            adapter: string;
                            display_name: string;
                        }[];
                        disabled?: {
                            adapter: string;
                            channel?: string;
                            version?: string;
                        }[];
                    };
                };
            };
        };
    };
    getOwnerBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            403: components["responses"]["OriginRejected"];
            /** @description 本装配未启用 owner token（owner_token_disabled） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listHarnessExecutables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 注册表列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        executables: components["schemas"]["Executable"][];
                    };
                };
            };
            503: components["responses"]["HarnessUnavailable"];
        };
    };
    addHarnessExecutable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualExecutableRequest"];
            };
        };
        responses: {
            /** @description 已登记 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "registered";
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            503: components["responses"]["HarnessUnavailable"];
        };
    };
    enableHarnessExecutable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 注册表唯一 ID（含路径，URL 编码传递） */
                id: components["parameters"]["ExecutableID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已启用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        /** @constant */
                        enabled: true;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description login_required（未登录不可启用） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["HarnessUnavailable"];
        };
    };
    disableHarnessExecutable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 注册表唯一 ID（含路径，URL 编码传递） */
                id: components["parameters"]["ExecutableID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已禁用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        /** @constant */
                        enabled: false;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["HarnessUnavailable"];
        };
    };
}
