/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针 */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 房间列表（UI 重设计切片 1）
         * @description 全量房间摘要，按 last_event_at 倒序（无事件的房间 last_event_at = created_at）。
         *     只读端点：与既有读面一致，不设 owner token 门（见本文档顶部形态约束）。
         */
        get: operations["listRooms"];
        put?: never;
        /** 创建房间（create_room 命令） */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{room_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交房间命令（post_message / pause_room / resume_room / rename_room 等） */
        post: operations["submitRoomCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{room_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE 订阅房间事件流（opaque cursor 续传）
         * @description 响应为长流 `text/event-stream`。游标语义：`?cursor=` 或 `Last-Event-ID`（重连）；
         *     先订阅后追平，position 去重兜底；慢消费者/追平失败发 `resync_required` 具名事件
         *     （data 含 reason）后断流，客户端携最后 id 重连或走快照。
         */
        get: operations["subscribeRoomEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{room_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 快照（版本 + 水位 + 投影/算法版本 + Timeline 投影 + 房间名/参与者视图） */
        get: operations["getRoomSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{room_id}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 房间记忆视图（胶囊 + 编辑历史 + 容量水位）
         * @description M3-3 记忆查看面（RFC-0007 §7.4 裁定 5）：已接受胶囊的编辑后视图
         *     （conclusions/assumptions 已应用 memory.edited 链，与语境注入同源不双轨）
         *     + edit_history（人工编辑留痕）+ capsule_budget（恒常平面容量水位——
         *     dropped_count > 0 即超预算倒逼合并的信号）。编辑走 edit_memory 命令。
         */
        get: operations["getRoomMemory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rooms/{room_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 房内消息全文检索（FTS5 trigram，按需平面）
         * @description M3-3 按需检索平面（RFC-0007 §3.1.8 v0.2）：SQLite FTS5 trigram——
         *     CJK 子串 ≥3 字与英文词均可用（v1.46 spike 实证）；<3 字查询回退
         *     子串匹配（语义一致）。结果最新在前，position 供时间线跳转定位。
         */
        get: operations["searchRoomMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前在席 Agent 座位（建房选择的候选集）+ 已发现未启用项
         * @description 引擎座位快照（已启用的真实适配器 + echo 基线）。participant_id 即建房
         *     create_room.payload.agents 项与 invite_agent 目标。座位随 harness 启停
         *     动态变化（10s resync）。disabled 为已发现但未启用的可执行项（v1.24：
         *     选人页如实展示"还有谁未启用"，指路设置）——仅有 adapter/channel/version，
         *     无 participant_id（未入席）。
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/owner/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 第一方客户端引导：返回 owner token（跨源门保护）
         * @description 仅在配置了 OwnerToken 的装配上注册。响应含写端点所需的 X-Owner-Token 值。
         *     读取本身过跨源门：Origin 存在且非信任源（回环/壳源）→ 403——DNS rebinding
         *     页面同源化后也读不到 token（写通道另由 Origin 门 + token 双重把守）。
         *     无 Origin 的本机客户端（curl/同源 GET）可达——同用户本机进程本就等效 owner。
         */
        get: operations["getOwnerBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/harness/executables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 宿主扫描到的 agent CLI 注册表 */
        get: operations["listHarnessExecutables"];
        put?: never;
        /** 手动登记 agent CLI（探测失败拒收） */
        post: operations["addHarnessExecutable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/harness/executables/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 启用可执行项（登录门控；启用后 ≤10s 入座，无需重启） */
        post: operations["enableHarnessExecutable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/harness/executables/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 禁用可执行项（座位随 resync 撤出） */
        post: operations["disableHarnessExecutable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 命令信封（RFC-0001）。payload 按 command_kind 严格校验（未知字段拒绝）：
         *     create_room → CreateRoomPayload；post_message → PostMessagePayload；
         *     pause_room → PauseRoomPayload；resume_room → 空 payload；
         *     rename_room → RenameRoomPayload（UI 重设计切片 1；room.renamed 事件）；
         *     endorse_intent → EndorseIntentPayload（OQ-17 人类保送，effect=grant）；
         *     invite_agent → {participant_id}（RFC-0001 Membership：participant.admitted 拉人）；
         *     fork/pause/resume/close/reopen/merge_thread → ThreadLifecyclePayload（RFC-0004 线程生命周期，
         *     状态机转移校验；merge 在个人版单 owner 形态下为直接命令=确认权）。
         */
        RoomCommand: {
            /** @enum {string} */
            command_kind: "create_room" | "post_message" | "pause_room" | "resume_room" | "rename_room" | "endorse_intent" | "invite_agent" | "fork_thread" | "pause_thread" | "resume_thread" | "close_thread" | "reopen_thread" | "merge_thread" | "propose_closure" | "accept_closure" | "create_evidence_request" | "resolve_evidence_request" | "resolve_task" | "edit_memory" | "delete_room";
            expected_room_version: number;
            /** @description UUIDv7（服务端按 tenant+key+kind 去重；同键异指纹 409） */
            idempotency_key: string;
            /** Format: date-time */
            issued_at: string;
            payload: Record<string, never>;
        };
        CreateRoomPayload: {
            display_name?: string;
            /** @description 入房 Agent（participant ID，见 GET /v1/agents）。缺省/空 = 全部在席；非空 = 恰好所选（后续可 invite_agent 拉人）。 */
            agents?: string[];
        };
        /** @description 房间改名载荷（room.renamed 事件载荷同构）；改名不接受置空/纯空白。 */
        RenameRoomPayload: {
            display_name: string;
        };
        RoomList: {
            rooms: components["schemas"]["RoomSummary"][];
        };
        RoomSummary: {
            room_id: string;
            /** @description 最新 room.created/room.renamed 投影 */
            display_name: string;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description 该房间最新事件时间（无事件则等于 created_at）；列表按此倒序
             */
            last_event_at: string;
            /** @description 最新生命周期事件为 room.paused */
            paused: boolean;
            /**
             * Format: int64
             * @description message.posted 类事件数
             */
            message_count: number;
        };
        /** @description 字段集与 events/message.posted.schema.json 对齐（M2 定稿）；relations 项不收 provenance（系统固化 explicit）。 */
        PostMessagePayload: {
            body: string;
            reply_to?: null | string;
            addressed_to?: string[];
            relations?: components["schemas"]["TypedRelationInput"][];
            thread_id?: null | string;
        };
        TypedRelationInput: {
            target_event_id: string;
            /** @enum {string} */
            kind: "supports" | "challenges" | "extends" | "questions" | "evidence_for" | "supersedes" | "analogy" | "relates";
        };
        PauseRoomPayload: {
            reason?: string;
        };
        /** @description 线程生命周期命令载荷（RFC-0004）。fork_thread 必填 source_event_id+goal；其余必填 thread_id；merge 另必填 merged_into。 */
        ThreadLifecyclePayload: {
            thread_id?: string;
            source_event_id?: string;
            goal?: string;
            participants?: string[];
            merged_into?: string;
            reason?: string;
        };
        /** @description 人类保送（RFC-0003 §3.1.11 / OQ-17）。effect=grant 直接授予 Floor（默认）；boost 未开放。不绕过预算/硬资格/安全；对全体可见。 */
        EndorseIntentPayload: {
            intent_id: string;
            /** @enum {string} */
            effect: "grant";
        };
        CommandResponse: {
            room_id: string;
            event_id: string;
            /** Format: int64 */
            room_version: number;
            replayed: boolean;
        };
        Error: {
            error: {
                /** @description 稳定错误码（transport 与 domain 映射） */
                code: string;
                message: string;
            };
        };
        /** @description 对外事件视图（RFC-0001 P0：无 seq/tenant_id，opaque position 替代）；payload 的事件族 Schema 见 api/room-protocol/events/。 */
        EventView: {
            event_id: string;
            room_id: string;
            thread_id?: null | string;
            type: string;
            schema_version: number;
            /** Format: date-time */
            occurred_at: string;
            actor: {
                participant_id: string;
                /** @enum {string} */
                kind: "human" | "agent" | "system";
            };
            causation_id?: null | string;
            correlation_id?: null | string;
            visibility: {
                /** @enum {string} */
                kind: "public" | "participants" | "moderators" | "system";
                participants?: string[];
            };
            payload: Record<string, never>;
            /** @description opaque cursor（续传位点） */
            position: string;
        };
        Snapshot: {
            room_id: string;
            /** Format: int64 */
            room_version: number;
            watermark: string;
            /** Format: int64 */
            projection_version: number;
            /** Format: int64 */
            algorithm_version: number;
            /** @description 房间名（room.created/room.renamed 投影产物） */
            display_name: string;
            /** @description 参与者视图（装配层注入：本地 owner + 引擎座位；非投影产物——ADR-0011 注记，不进 room_version/水位语义）。 */
            participants: components["schemas"]["ParticipantView"][];
            /** @description 房间成员投影（room.created.agents + participant.admitted 链；null/缺 = 全部在席）。 */
            roster?: string[];
            /** @description 线程投影（RFC-0004 生命周期状态 + fork 谱系 + 合并去向）。 */
            threads: {
                thread_id: string;
                /** @enum {string} */
                state: "active" | "paused" | "closed" | "merged";
                parent?: string;
                goal?: string;
                merged_into?: string;
                message_count?: number;
            }[];
            /** @description 显式关系边（forked_from/responds_to/merged_into + relations 类型化边）。推断边属结构投影（M3），接入后标 inferred=true——双视图显式与推断区分。 */
            graph: {
                kind: string;
                from: string;
                to: string;
                inferred: boolean;
            }[];
            /** @description 记分卡（R-08/OQ-17：intent 全量投影，band + 未选理由 + 保送状态）。 */
            scorecard: {
                intent_id: string;
                participant_id: string;
                type?: string;
                action?: string;
                score_band: string;
                selected: boolean;
                endorsed: boolean;
                public_rationale?: string;
                unselected_reason?: string;
                round_id?: string;
                /** Format: date-time */
                occurred_at?: string;
            }[];
            timeline: components["schemas"]["TimelineItem"][];
            /** @description 收束清单（M3-2：pending 可接受 / accepted / rejected 各一条摘要）。 */
            closures?: components["schemas"]["ClosureSummary"][];
            /** @description 任务清单（M3-3 tasklist，RFC-0012 OQ-A：带责任人 owner 的承诺追踪——确定性派生 + 人工门控裁定）。 */
            tasks?: components["schemas"]["TaskItem"][];
            /** @description 证据需求单（M3-5：open/resolved/dismissed）。 */
            evidence_requests?: components["schemas"]["EvidenceRequestView"][];
            /** @description 开发者模式回放条目（M3-1 持久化补全：事件支撑的 [dev] 内联信息，重启还原）。 */
            dev_notes?: components["schemas"]["DevNote"][];
        };
        DevNote: {
            position: string;
            event_id: string;
            type: string;
            /** Format: date-time */
            occurred_at: string;
            payload: Record<string, never>;
        };
        EvidenceRequestView: {
            request_id: string;
            claim_id?: string;
            question: string;
            required_evidence?: string[];
            acceptance_criteria?: string;
            owners?: string[];
            /** @enum {string} */
            status: "open" | "resolved" | "dismissed";
            evidence_refs?: string[];
            reopen_thread_on_resolution?: boolean;
        };
        ClosureSummary: {
            closure_id: string;
            thread_id: string;
            /** @enum {string} */
            state: "pending" | "rejected" | "accepted";
            /** @enum {string} */
            closure_type?: "consensus" | "bounded_disagreement";
            ready: boolean;
            evaluated: number;
            concluded: number;
            objected: number;
            reason?: string;
        };
        ParticipantView: {
            participant_id: string;
            /** @enum {string} */
            kind: "human" | "agent" | "system";
            /** @description 引擎已知名字（Owner/Echo/Codex/Kimi 等） */
            display_name: string;
            /** @description agent 座位的适配器名（human 无此键） */
            adapter?: string;
            /** @description harness 渠道标签（cli/app:codex-desktop 等；无则省略） */
            channel?: string;
            /** @description seated（在座；离座语义随 UI 重设计后续切片定稿） */
            seat_status: string;
        };
        /**
         * @description RFC-0012 群聊模型：Timeline = 消息族 + 暂停/恢复系统提醒（round.* 内部化，
         *     不入用户可见时间线）。
         */
        TimelineItem: {
            position: string;
            event_id: string;
            type: string;
            actor_id: string;
            actor_kind: string;
            body?: string;
            thread_id?: null | string;
            /** Format: date-time */
            occurred_at: string;
        };
        Executable: {
            /** @description 注册表唯一 ID（adapter@runtime:path） */
            id: string;
            adapter: string;
            /** @description native | wsl */
            runtime: string;
            /** @description WSL 运行面的发行版（native 为空） */
            distro?: string;
            path: string;
            version?: string;
            /** @description sha256（版本固定门禁用） */
            digest?: string;
            /** @description logged_in | logged_out | unknown */
            login_state?: string;
            /** @description auto_scan | manual */
            source?: string;
            /** @description 实例渠道（ADR-0012）：cli | app:codex-desktop | app:kimi-work */
            channel?: string;
            /** @description 家族裁定优先级（数值小者优先；列表已按 adapter→priority→path 排序） */
            priority?: number;
            /** Format: date-time */
            discovered_at?: string;
            enabled: boolean;
        };
        ManualExecutableRequest: {
            adapter: string;
            runtime: string;
            distro?: string;
            path: string;
            version?: string;
            /** @description 可选渠道覆盖（cli 或 app:<小写>），空值按 cli */
            channel?: string;
        };
        /** @description 任务清单项（M3-3 tasklist）：确定性派生（agent 消息宣言句）+ 人工门控裁定（task.resolved）。 */
        TaskItem: {
            /** @description tsk_ 前缀（源事件哈希派生，确定性） */
            task_id: string;
            /** @description 责任人（承诺者 participant_id——多 Agent 群聊对常见 tasklist 的必要增量） */
            owner: string;
            /** @description 宣言句（截断 120 字） */
            text: string;
            /** @description 派生源消息（provenance 跳转位） */
            source_event_id: string;
            /** Format: date-time */
            declared_at: string;
            /** Format: int64 */
            declared_seq: number;
            /** @description 声明后经过的波数 */
            waves_since: number;
            /** @description pending 且 waves_since ≥ 2 */
            overdue: boolean;
            /** @enum {string} */
            status: "pending" | "delivered" | "dismissed";
            resolution?: string;
            note?: string;
            resolved_by?: string;
            /** Format: date-time */
            resolved_at?: string;
        };
        /** @description 任务裁定（task.resolved 事件载荷）：delivered=已交付；dismissed=误报/撤销。 */
        ResolveTaskPayload: {
            task_id: string;
            /** @enum {string} */
            resolution: "delivered" | "dismissed";
            note?: string;
        };
        /** @description 胶囊记忆人工编辑（memory.edited 事件载荷）：conclusions/assumptions 为编辑后全文（整组替换），至少一项提供。 */
        EditMemoryPayload: {
            /** @description 胶囊 closure_id */
            memory_id: string;
            conclusions?: string[];
            assumptions?: string[];
            /** @description 编辑理由（留痕） */
            note?: string;
        };
        /** @description 记忆查看面（GET /v1/rooms/{id}/memory）：编辑后胶囊 + 容量水位。 */
        MemoryView: {
            room_id: string;
            capsules: {
                closure_id: string;
                /** @enum {string} */
                closure_type: "consensus" | "bounded_disagreement";
                thread_id: string;
                /** Format: int64 */
                watermark?: number;
                conclusions: string[];
                assumptions: string[];
                named_dissent: {
                    participant_id: string;
                    basis: string;
                }[];
                falsifiers?: string[];
                reopen_triggers?: string[];
                /** @description 人工编辑留痕（正文在事件流；此处只留溯源位） */
                edit_history: {
                    event_id: string;
                    edit_version: number;
                    note?: string;
                    edited_by: string;
                    /** Format: date-time */
                    occurred_at: string;
                }[];
            }[];
            /** @description 恒常平面容量水位（Hermes 纪律：dropped_count > 0 即超预算——倒逼合并/编辑，不静默截断） */
            capsule_budget: {
                budget_runes: number;
                injected_runes: number;
                injected_count: number;
                dropped_count: number;
            };
        };
        /** @description 检索命中（对外视图：无 seq/tenant；position 供时间线跳转）。 */
        SearchHit: {
            event_id: string;
            actor: string;
            /** @enum {string} */
            actor_kind: "human" | "agent" | "system";
            thread_id?: null | string;
            body: string;
            /** Format: date-time */
            occurred_at: string;
            /** @description opaque cursor（时间线定位） */
            position: string;
        };
    };
    responses: {
        /** @description 请求不合法（bad_request / invalid_command / bad_cursor / bad_limit / invalid_entry） */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 跨源拒绝（origin_rejected——本地 owner API） */
        OriginRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 缺少或错误的 X-Owner-Token（owner_token_required） */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 版本冲突 / 幂等键指纹冲突（version_conflict / idempotency_conflict） */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 房间或条目不存在（room_not_found / not_found） */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求体超过 1MiB（body_too_large） */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Content-Type 须为 application/json（unsupported_media_type） */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 宿主注册表未配置（harness_unavailable） */
        HarnessUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 服务端错误（internal / snapshot_failed） */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        RoomID: string;
        /** @description 注册表唯一 ID（含路径，URL 编码传递） */
        ExecutableID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    listRooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 房间列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomList"];
                };
            };
            500: components["responses"]["Internal"];
        };
    };
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "command_kind": "create_room",
                 *       "expected_room_version": 0,
                 *       "idempotency_key": "018f6b2e-7c1a-7b3d-9e4f-1a2b3c4d9001",
                 *       "issued_at": "2026-08-30T09:30:00.000Z",
                 *       "payload": {
                 *         "display_name": "第一个房间"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["RoomCommand"];
            };
        };
        responses: {
            /** @description 命令受理（含幂等回放） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    submitRoomCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomCommand"];
            };
        };
        responses: {
            /** @description 命令受理（含幂等回放） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    subscribeRoomEvents: {
        parameters: {
            query?: {
                /** @description opaque 游标（空 = 从头）；与 Last-Event-ID 同义，query 优先 */
                cursor?: string;
            };
            header?: never;
            path: {
                room_id: components["parameters"]["RoomID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 事件流（SSE） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getRoomSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 快照 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    getRoomMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: components["parameters"]["RoomID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 记忆视图 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryView"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    searchRoomMessages: {
        parameters: {
            query: {
                /** @description 检索词（子串语义） */
                q: string;
                /** @description 按参与者过滤（participant_id） */
                actor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                room_id: components["parameters"]["RoomID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 命中列表（最新在前） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        hits: components["schemas"]["SearchHit"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 座位列表 + 未启用项 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agents: {
                            participant_id: string;
                            adapter: string;
                            display_name: string;
                        }[];
                        disabled?: {
                            adapter: string;
                            channel?: string;
                            version?: string;
                        }[];
                    };
                };
            };
        };
    };
    getOwnerBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            403: components["responses"]["OriginRejected"];
            /** @description 本装配未启用 owner token（owner_token_disabled） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listHarnessExecutables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 注册表列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        executables: components["schemas"]["Executable"][];
                    };
                };
            };
            503: components["responses"]["HarnessUnavailable"];
        };
    };
    addHarnessExecutable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualExecutableRequest"];
            };
        };
        responses: {
            /** @description 已登记 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "registered";
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            503: components["responses"]["HarnessUnavailable"];
        };
    };
    enableHarnessExecutable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 注册表唯一 ID（含路径，URL 编码传递） */
                id: components["parameters"]["ExecutableID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已启用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        /** @constant */
                        enabled: true;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description login_required（未登录不可启用） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["HarnessUnavailable"];
        };
    };
    disableHarnessExecutable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 注册表唯一 ID（含路径，URL 编码传递） */
                id: components["parameters"]["ExecutableID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已禁用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        /** @constant */
                        enabled: false;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["HarnessUnavailable"];
        };
    };
}
